- README.md
- extension.js
- src/Instance.js
- src/views/memberBrowser.js
- src/views/qsysFs.js
- src/webviews/login/index.js
This was quite a weird one because I didn't encounter any issues on Windows at all. Perhaps it's Windows or different versions of Node that makes file naming a little more relaxed, I'm still a bit confused. 
I encountered the same error as https://github.com/halcyon-tech/code-for-ibmi/issues/14 on Ubuntu 20.04.2 and VS Code 1.53.2.
```
Activating extension 'halcyontechltd.code-for-ibmi' failed: Cannot find module './src/instance'
Require stack:
- /home/barrett/Programming/code-for-ibmi/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js.
```
I debugged it locally and found that multiple files had a problem resolving the paths to 'Instance.js'
So, I changed the import paths …
> fix Instance class not found on linux

- docs/README.md
- package.json
- src/Instance.js
- src/api/CompileTools.js
- src/api/IBMiContent.js
- src/views/objectBrowser.js
Covers issue #26. This adds an object browser to the IBM i view. I am using the same caching technique used in the member browser by @barrettotte.
Right-click contexts include:
* Run Action
> Start of object browser (#26)

- README.md
- src/webviews/login/index.js
Correct port field on login to be named port.
> Correct field name on login form

- README.md
- docs/README.md
- src/api/IBMi.js
- src/webviews/login/index.js
Simple attempt to introduce connectivity with SSH private keys. I've only tested on Windows, but I've no reason to believe that this shouldn't work on Linux/Mac as well.
Limitations: this won't be useful for SSH keys protected with a passcode.
`docs/README.md` could use a couple of updated screenshots for the connection window (i.e. `login_03.png` and `login_04.png` in `docs/assets/`). I've omitted them for now, as the look and feel of my editor wouldn't be consistent with the rest of the document. Could you possibly add them in for me please?
I've also bumped the list of contributors to the bottom of the main README. Controversial, I know! However, it was getting so long that it obscures the useful information a first time reader would want to see. I can restore this to its original …
> Add option to connect with SSH private key

- docs/README.md
- package.json
- src/Instance.js
- src/api/CompileTools.js
Solves #98 
* able to use `&BUILDLIB` in Member actions and the library list.
* new command to change build library
* print library list to output channel when running an action
> &BUILDLIB for member actions and library list

- README.md
- package.json
This change adds CRTCMD for streamfiles for the default actions.
It also fixes the default CRTCMD commands for members (misspelled variable).
> Add CRTCMD for streamfiles

- package.json
- src/api/CompileTools.js
- src/api/Configuration.js
- src/webviews/settings/index.js
Adds brand new configuration to hide specific errors from the compile log.
> New config to hide specific compile codes (#132)

- src/Instance.js
- src/api/Disposable.js
- src/extension.js
* Gives specific functionality IDs on their Dispose instances so other plugins can dispose of specific base functionality (in case they want to replace it)
* Expose the base context so other plugins can control them.
> Expose context

- docs/README.md
- package.json
- src/Instance.js
- src/api/CompileTools.js
- src/api/Configuration.js
- src/api/IBMi.js
This fix will rename 'build library', to 'current library'. We're doing this for many reasons:
* It makes more sense to IBM i devs
* We can actually set the builds current library at compile time now
> Use current library over build library

- .gitignore
- README.md
- package.json
- src/api/IBMiContent.js
- src/views/ifsBrowser.js
Basic IFS upload and download functionality implemented as requested in #45.
Very simple but a start.
You're able to download files from the IFS browser with right-click and "Download".
There are two way's to upload files:
1. Use the upload icon in the IFS browser header
2. Use right-click and "Upload" on a directory
During development, I made a note of the following points to consider for the future:
1. Does it work correctly on Windows? I've tested it on macOS. Maybe there are some path specialties on another OS?
2. I've not tested the up- and download of files with a large size. The IBMiContent class is very basic at the moment and currently not supporting progress tracking.
3. Up- and downloading of directories didn't work yet
4. Only utf8 files are supported at the moment because of …
> Basic IFS up- and download functionality

- src/Instance.js
- src/api/IBMi.js
Create an output channel for all remote commands. This will be used to mostly help users debug their issues. It will allow them to share with us the commands and output they get for us to debug the issues.
> Create output channel for all remote commands

- src/Instance.js
- src/views/memberBrowser.js
In IBM i land, it is not uncommon for files to include weird characters - in this case, a pound sign, or hash tag, depending on where you're from.
This PR fixes the issue where [VS Code's Uri class](https://code.visualstudio.com/api/references/vscode-api#Uri) was parsing a path such as `BARRY/QRPGLESRC/PGM#01.rpgle` as `BARRY/QRPGLESRC/PGM` and treating `01.rpgle` as the Uri fragment. Same goes for IFS paths.
This will close #169.
> Allow files with poundsigns to be opened (#169)

- src/api/IBMi.js
- src/api/IBMiContent.js
An issue was reported where `ls` was writing to standard out, even if files existed but a single file had a badly encoded name. This solves that by always printing the file listing, even if there is an error.
> Show IFS listing, even if standard out is printed too (#168)

- src/api/Search.js
Looks like only members were really escaping certain characters when it should have been for the IFS too.
Fixes #165
> Handle better regex on IFS and member search (#165)

- src/views/ifsBrowser.js
Fixes an issue where downloading content from the IFS would crash due to an invalid path.
> Fix for downloading IFS content on Windows

- docs/README.md
- package.json
- src/api/Configuration.js
- src/views/libraryListView.js
This adds two new buttons to the library list view that will allow users to save library lists (namely a Library List Profile) and change between them.
Will close #204.
> Allow the user to have many library lists (#204)

- src/api/IBMi.js
There is an issue that when the current library doesn't exist when the temp library can't be created that the connect process would crash. This adds a warning for that.
Potential fix for #214
> Add warning when tempLibrary is not set correctly

- package.json
- src/views/objectBrowser.js
Libraries can now be created via the object browser. You'll find a new + icon on the right of "OBJECT BROWSER". This feature was requested in #194.
Please check the following things before merging:
1. Is it working properly? Unfortunately it's not allowed to create new libraries on PUB400. So I couldn't test it properly.
2. Is the "+" icon good for this use case? In my opinion the icon with the directory and a "+" would fit better but it was already used.
> Library creation via object browser added

- package.json
- src/views/memberBrowser.js
Added functionality to upload and download source members. (See issue #46)
It's now possible to up- and download source members by right-clicking the member name in the member browser.
Something to consider: The path routines in code-for-ibmi.uploadAndReplaceMemberAsFile and code-for-ibmi.downloadMemberAsFile are pretty similar to the routines in qsysFs.readFile. Maybe it make more sense to exclude it into an own util class. As far as I can tell, it makes more sense from my point of view to get the qsysFs stuff into the api.
> Added functionality to upload and download source members.

- package.json
The Move function can let the user Rename the IFS file, but that wasn't clear from the label.
If "Rename or Move object" is too long, "Rename/Move object" might also work.
> Add "Rename" to "Move object" menu command

- package-lock.json
- src/api/IBMiContent.js
Allow the user of `*ALL` for the source file name in the source file shortcuts.
Closes #269.
> Support *ALL as source file name

- package.json
- src/api/Configuration.js
- src/api/IBMi.js
- src/views/ifsBrowser.js
Implements the ability to have access to many IFS directories at the same time - these are called Shortcuts.
To do:
> Implementation of IFS shortcuts

- package.json
- src/api/Search.js
* Adds new global config `grepIgnoreDirs` which is used when searching the IFS
* IFS search API will use the config when search to keep searches from growing large.
> The ability to specify directories to ignore in the search

- package.json
The __pycache__ directory contains bytecode-like files that should be ignored when we run grep over source code.
> Ignore __pycache__ when searching Python source code

- package.json
Created a compiled COBOL module option
Created a compiled COBOL bundle(Module and Program) option
Added 2 compile option for COBOL:
{
"type": "member",
"extensions": [
"CBLLE",
"CBL"
],
"name": "Create ALL-in-one PGM CBLLE (CRTBNDCBL)",
"command": "CRTBNDCBL (&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
},
{
"type": "member",
"extensions": [
"CBLLE",
"CBL"
],
"name": "Create Module CBLLE (CRTCBLMOD)",
"command": "CRTCBLMOD MODULE(&OPENLIB/&OPENMBR) SRCFILE(&OPENLIB/&OPENSPF) OPTION(*SOURCE) DBGVIEW(*SOURCE)"
},
> Added 2 COBOL compile options

- src/views/connectionBrowser.js
- src/webviews/login/index.js
- src/webviews/settings/index.js
Implemented secret password storage. 
There is now the option to save a password for a new connection. 
For existing connections one can be set/changed via the new login settings page. 
Deleting a connection will also delete the saved password
"Save passwords" uses the VS Code secrets API and from windows can be seen/removed/amended in "Control Panel > Credential Manager > Windows Credentials"
> Save passwords

- package.json
- src/Instance.js
- src/api/Configuration.js
- src/webviews/settings/index.js
* Adds new config to auto save before an action is run
* Popup to save file before executing an action now has a `Save automatically` button which will update the config.
Closes #365
> New functionality to automatically save before an action is run (#365)

- package.json
Adds right-click option to the editor to launch the column assist.
> Add right click option for RPG to launch column assist (#369)

- src/views/ifsBrowser.js
- src/views/objectBrowser.js
Remove the use of the word 'Searching' appearing twice in the prompt.
> Remove use of word Searching twice

- src/api/Search.js
- src/views/objectBrowser.js
Previously the member search was not accounting for ASP defined in the settings. Now, not only will it use the ASP in the search, but it will also show the ASP in the search box.
Fixes #398
> Search in ASP when defined

- docs/README.md
- package.json
- src/Instance.js
- src/api/Configuration.js
- src/api/IBMi.js
- src/api/terminal.js
- src/webviews/settings/index.js
* Adds the ability to launch interactive shells/terminals using the same connection
* pase
* 5250 (depends on `/QOpenSys/pkgs/bin/tn5250`, available through yum)
* Upgrades required VS Code version.
> Support for IBM i terminals

- package.json
- src/api/Configuration.js
- src/api/terminal.js
- src/webviews/settings/index.js
* Adds two new config options for 5250
1. 5250 terminal
2. Set custom device name
* Fix for resizing issues
> New 5250 config & resize fix

- package.json
`logCompileOutput` enabled by default
> logCompileOutput enabled by default

- package.json
- src/Instance.js
As suggested on IBMiOSS Ryver, you can now open errors from an EVFEVENT file without having to run a compile command.
* Adds `code-for-ibmi.openErrors`
> New command to open errors from EVFEVENT

- docs/README.md
- package-lock.json
- package.json
- src/Instance.js
- src/api/CompileTools.js
- src/api/CustomUI.js
- src/api/Deployment.js
- src/webviews/actions/index.js
Adds the ability to deploy a VS Code workspace folder. Change list:
* New right-click menu to deploy to a certain IFS directory
* New status bar icon to Deploy current workspace folder(s)
* New Action type for 'file' (local files)
* New Action option to run the deploy before running the Action
> Workspace deploy

- src/Instance.js
- src/api/CompileTools.js
- src/api/IBMi.js
* Action standard out and error now writes to IBM i Output in real-time (much better when using build tools like BoB and GNU Make)
* The Actions button now will turn into a spinner when an Action is running.
> Improvements to action execution

- src/api/CompileTools.js
- src/webviews/actions/varinfo.js
* Fix for Windows when running an Action against a local file
* Adds `&RELATIVEPATH` for both `streamfile` and `file` types.
> Fix for building from local on Windows

- docs/api/extending.md
- src/Instance.js
- src/api/CompileTools.js
- src/api/IBMi.js
- src/api/IBMiContent.js
- src/filesystems/qsys/complex/content.js
- src/views/databaseBrowser.js
* Ability to let the user run statements without having `db2util` installed.
* New runQuery command for other extensions to make use of.
> New way to run statements without db2util

- src/api/IBMi.js
Make it easier to copy and paste the CHGUSRPRF command by removing the period after it. First time I pasted the command, it included the period and didn't work. (Very helpful message, incidentally!)
You can see how the period would end up copy/pasted accidentally.
> Remove period after home directory command

- package.json
- src/Instance.js
- src/api/Configuration.js
- src/api/IBMiContent.js
- src/views/databaseBrowser.js
- src/webviews/settings/index.js
* Adds new configuration to let the user select which SQL tool should be used to run SQL statements.
> Add sqlExecutor config to let user choose which CLI tool to use

- package.json
- src/api/Configuration.js
- src/api/IBMi.js
- src/api/IBMiContent.js
- src/webviews/settings/index.js
New functionality to auto-convert from and to EBCDIC for streamfiles
* New connection setting to enable this feature
> Support for EBCDIC streamfiles

- docs/README.md
- docs/api/extending.md
- package.json
- src/Instance.js
- src/api/Configuration.js
- src/api/IBMi.js
- src/api/IBMiContent.js
- src/api/Tools.js
- src/filesystems/qsys/complex/content.js
- src/views/databaseBrowser.js
- src/webviews/settings/index.js
* Removes SQL executor configuration
* Adds enable SQL configuration back
* Remove usage of `db2` and `db2util`
> Remove executor config, db2 and db2util from extension

- package.json
- src/views/libraryListView.js
* Adds new command to let the user edit the library list in the form of a string.
* Adds button in library list view to run command
> Editable library list as string

- package.json
- src/api/Configuration.js
- src/api/terminal.js
- src/webviews/settings/index.js
Adds a new config prop to make the 5250 connection string configurable.
> 5250 connection string now configurable

- package-lock.json
- package.json
- src/api/Search.js
* Escapes all search strings so regex is ignored.
* IFS search is now case in-sensitive (same as how member search works)
Fixes #165.
> Correctly escape input for regex characters

- package.json
- src/Instance.js
- src/languages/general/ColorProvider.js
- src/languages/general/colors.js
SEU users love to use colors in their source code. This only really worked in SEU since it affected the 5250 byte stream, but I simply parse out the source and make the lines change based on the character code.
Needs a bunch of testing before release. Implements #552
> Parse 5250 stream colors

- docs/README.md
- src/api/Deployment.js
add option to deploy "Working Changes" in addition to existing "Staged Changes" and "All" options.
@worksofliam I am using var instead of let for the changeType variable and am seeing the ESLint warning ["Unexpected var, use let or const instead"](https://eslint.org/docs/rules/no-var). Using let results in the execution ending unexpectedly when that line is encountered. Using const is not an option because this variable can be updated. How would you like me to address this?
> add option to deploy "Working Changes"

- package-lock.json
- src/views/libraryListView.js
Allow library list to be delimited by commas and/or spaces(s)
Remove duplicate libraries from the library list (keep first occurrence).
Add more specific check of stderr to determine library in error.
> Allow library list to be delimited by commas and/or spaces(s)

- src/views/ifsBrowser.js
add filter and concat to have directories list before streamfile list in the ifs browser.
> IFS browser directories before streamFiles

- package.json
add actions : 
- RUNSQLSTM (streamfile and member)
- CRTSQLRPGI (module) (streamfile and member)
- CRTSRVPGM (streamfile and member)
not CRTPGM because it already exist for global
> New default actions #568

- CONTRIBUTING.md
- src/api/IBMi.js
Example system has setccsid, iconv, and attr installed in `/usr/bin/`. The path `/QOpenSys/pkgs/bin/` does not exist.
When trying to use the "Support EBCDIC streamfiles" feature, an error message appears: `EBCDIC streamfiles will not be rendered correctly since attr or iconv is not installed on the host. They should both exist in \usr\bin\.`
If the directory `/QOpenSys/pkgs/bin/` is created, even if nothing is installed to it, the feature works as expected.
Exchange the `try (for) catch` remoteApps uses to check paths for a `for (try catch)` that allows the `for` loop to continue.
> Fix catch for missing directory

- src/api/IBMiContent.js
This PR will change the reading of directories in the IFS browser to mark symbolic links to directories as regular directories and let them be opened like any other directory.
> Open symlinks to directories like normal directories in IFS browser

- src/api/IBMiContent.js
- src/api/Search.js
- src/api/Tools.js
- src/views/ifsBrowser.js
This PR allows handling of special characters in path names in the IFS browser.
The remote path will have the special characters quote, double-quote, dollar sign, backslash and the space escaped before using the path name. The list of characters is not complete but can be extended - it only contains the characters that I personally experienced problems with.
Now you can use all operations in the IFS browser even when the path contains the above mentioned special characters.
> Allow special chars in IFS browser

- src/api/CompileTools.js
- src/api/IBMi.js
- src/api/IBMiContent.js
- src/api/Search.js
- src/api/errors/format.js
- src/api/errors/handlers/new.js
- src/api/errors/handlers/old.js
- src/filesystems/qsys/complex/handler.js
- src/languages/clle/clCommands.js
- src/views/ifsBrowser.js
- src/views/objectBrowser.js
This PR will remove all use of the deprecated string method substr(), mostly by using substring() instead.
The difference in the second parameter is only a problem when the first parameter is not zero, and it has been changed into <start>+<length>.
> Eliminate deprecated string method substr()

- src/api/Search.js
- src/views/objectBrowser.js
This PR will
- enhance the member search feature to respect any member type filter.
- fix error received when member filter is not ending in `*`.
- fix empty result set when searching in only one member in filter.
> Make member search respect member type filter

- src/api/IBMiContent.js
- src/api/Search.js
- src/views/objectBrowser.js
This PR will
- make both member name and member type in lowercase in the search result window - previously member name was uppercase while member type was lowercase.
- sort the search result list in local order - instead of the server order which was American and did not correspond to the local order when the variant characters were vowels.
> Minor improvements to the member search function

- src/webviews/filters/index.js
Most people initially want to open source code, so it makes sense to make to make the default object filter `*SRCPF` for that reason.
> Change default object filter to source file

- src/webviews/actions/index.js
This PR has the following improvements to action management:
- Duplicated actions are not saved before confirmation. The action selected for duplication will be shown in the action edit panel, where the user can change and save the action.
- The title for the action panel is changed according to the operation, e.g. `Change action "xxxx"` when changing an action. Previously the title was always `Work with Actions`.
- A button labeled `Cancel` is added to all action management panels. This is more intuitive for cancelling the operation and go back to the list of actions than having to close the panel using Ctrl-W or click on X.
- The action edit panel will stay on screen if the user clicks `Delete` and then selects No or cancel on the confirmation message. However, the changed values will …
> Action management improvements

- docs/pages/developing/local-development.md
- package.json
- src/api/Deployment.js
- src/schemas/localLanguageActions.js
Adds new UX for automatically creating an `actions.json` file if it does not exist.
> Local actions automated setup

- src/views/profilesView.js
When saving current settings into profile, propose the current profile.
I was wanting to use a pattern. These can be long enough to be problematic when retyping the name.
> Propose current profile.

- src/webviews/settings/index.js
New logic was added to the connection settings browser which was causing an issue when trying to show the settings prior to connecting.
> Fix bug not showing the connection settings prior to connection

- package.json
- src/views/libraryListView.js
This is a quick PR to provide a solution for the discussion in #751 and show the current library at the top of the library list.
I agree with Jon that it would be beneficial to see the current library - it is after all a part of the complete library list and is used during compile and other commands.
The current library has been given a special context value of `currentLibrary` to mark the object and omit the actions for moving up and down. Also the description is `(current library)`.
> Show current library in library list

- package.json
- src/api/Configuration.js
- src/api/IBMiContent.js
- src/views/libraryListView.js
- src/webviews/settings/index.js
This PR will add a configuration value to allow showing library description and attribute in the User Library List view.
This was made optional, since it is quite slow to retrieve the description and attribute for the libraries when SQL is not enabled.
Two techniques were tested during development:
1. retrieving information for one library at a time and
2. retrieving information for all libraries and filter according to the library list
The second option was chosen since there did seem to be any speed difference and this option was easier to code.
> Option to show library description and attribute in User Library List view

- src/api/CompileTools.js
- src/views/libraryListView.js
Support for libraries with dollar signs in the name when managing the library list.
Fixes #873
> Fix for libraries with dollar signs in the name

- package.json
- src/views/objectBrowser.js
This PR will add a configuration option to show names and types in lowercase or original (upper/mixed) case:
The option will be enabled by default to make the extension work as before this option. The user will have to disable it to have names shown in uppercase / mixed case.
Here is a sample screenshot with the option disabled:
And another screenshot of a member list (IBM provides the text for files and members in QSYSINC as uppercase, this is not done by the extension):
IMHO this option should be disabled by default to make the extension more familiar to old-school IBM i people. I myself prefer names in the /QSYS.LIB filesystem (objects and members) to be shown in uppercase. This would however change the visual of this extension, and that may not be what you want. So I have set it to …
> Add option to show names in uppercase

- src/views/objectBrowser.js
This PR adds icons for some object types in the object browser. The object types are
*DTAARA
*DTAQ
*JOBQ
*LIB
*MEDDFN
*OUTQ
*PNLGRP
*SBSD
*SRVPGM
*USRSPC
> Add some object type icons in object browser

- src/filesystems/qsys/complex/content.js
Fix for #883. Uses QSYS2/SYSTABLES to get ROW_LENGTH-12 when unable to get a row length using LENGTH(srcdta) when using SQL (Source Dates enabled)
> Fix for #883 - Uses ROW_LENGTH from SYSTABLES for new source members

- src/views/ifsBrowser.js
- src/views/objectBrowser.js
This PR will fix issue #891 and show the search term and the search path when showing "No results found."
> Show search term and path when no results found

- src/api/Deployment.js
@edmundreinhardt found an issue where the new deployment `Changes` option was not taking the gitignore into account.
This PR will:
* Fix issue where status bar button would continue to spin after failure
* Enable the View Log button to actually work
* Check the gitignore when uploading files to the server when using the `Changes` option.
> New Deployment option `Changes` not taking gitignore into account

- src/filesystems/qsys/complex/content.js
- src/filesystems/qsys/complex/data.js
- src/filesystems/qsys/complex/handler.js
Fix to alias path to use double quotes to allow for dots and other characters in the object names.
Was assisted by @forstie on this fix.
Fixes #912.
> Use double quotes in SQL alias member path

- package.json
- src/views/profilesView.js
Adds new 'create new profile' button instead of re-using save button.
Fixes #920.
> New create profile button

- src/views/libraryListView.js
"Add to library list" action is broken as soon as a library is selected in the view. Once this happen, the command receives the selected node in parameter, and never prompts for a name anymore, which results in the error message "Library is too long." being displayed right away.
Checking if the "newLibrary" parameter is actually a string fixes the issue.
> Fixed "Add to library list" action

- src/views/profilesView.js
The "Name of profile" input box would show "[Object object]" as the default value when no "last profile name" is already stored.
> Fixed "Name of profile" prompt

- package-lock.json
- src/api/Configuration.ts
- src/api/Instance.ts
During the conversion to TS, `config#get` and `config#set` were removed. Turns out, the vscode-db2i and code-coverage-ibmi extensions relied on those API heavily to store connection specific configuration.
This PR adds `instance#setConfig` to allow external extensions to update connection configs, as well as add their own configurations.
Fixes are in places for those extensions to use this new API when this is merge:
* vscode-db2i: https://github.com/halcyon-tech/vscode-db2i/commit/a6070a2d4a844f2eb336cf1e1baedf884032fb21
* code-coverage-ibmi: https://github.com/halcyon-tech/code-coverage-ibmi/commit/4f687b1959255d3d99c234f63ba13693ca66cc59
> FIX: Ability for extensions to get and change config

- src/api/Deployment.js
- src/global.d.ts
- src/schemas/LocalLanguageActions.ts
@worksofliam I started from scratch since it was a small change. It's cleaner this way.
* Converted `LocalLanguageActions` to TypeScript
* `type` in `Action` is now optional (or `type` would have to be defined on every predefined action)
> Converted LocalLanguageActions to TypeScript

- src/views/objectBrowser.js
ILEObject icon would always be `circle-large-outline` when the `showNamesInLowercase` setting was true, because the object's type would be lowercase and wouldn't match the icons array's.
> Fixed ILEObject icon

- package.json
- src/global.d.ts
- src/views/objectBrowser.js
A small change to add Object's attribute to the `ILEObject` tree item contextValue.
This will allow extensions to define actions for some specific sub-type of objects.
"Completely random" example: define an action only for Save Files
```
{
"command": "vscode-ibmi-fs.downloadSavf",
"when": "view == objectBrowser && viewItem == object.file.savf",
"group": "1_savfActions@1"
}
```
This PR also introduce the `IBMiObject` interface (that ILEObject virtually implements) for easier access to the tree item fields.
> Add Object attribute to ILEObject tree item context value

- src/Instance.ts
As requested by other extension developers, this provides the ability to store connection specific secrets.
After this PR has been tested, the API docs should be updated.
New VS Code command API to get/set connection secret.
```ts
// to get
const theAdminUser = await vscode.commands.executeCommand(`code-for-ibmi.secret`, `adminUser`);
// to set
const theAdminUser = await vscode.commands.executeCommand(`code-for-ibmi.secret`, `adminUser`, `QSECOFR`);
```
> New API to set and get connection secret

- src/api/local/deployment.ts
Fixed `launchActionsSetup` crashing right at the beginning because of a wrong call to `getWorkspaceFolders` prefixed by `module.exports` (how I let that slipped is still a mystery...sorry!).
> Fixed launchActionsSetup crashing

- src/sandbox.ts
Brand new methods to spin up the sandbox environment.
Now accepts environment variables for connection details, which might be useful on private clouds with the use of on-prem code server instances (code-server, Gitpod, Coder.com)
* `SANDBOX_SERVER`
* `SANDBOX_USER`
* `SANDBOX_PASS`
For public sandbox environments, the branch name can support a hostname/IP address.
* Just username, which grabs the server from `SANDBOX_SERVER`: `JUNK5`
* New, which allows for server and username: `SERVER/JUNK5`
> Support more dynamic sandbox

- src/api/local/deployment.ts
no longer match on **/.gitignores
so it only finds .gitignore in root
* [x ] have tested my change
* [x ] Remove any/all `console.log`s I added
* [ x] eslint is not complaining
> **/.gitignores causes deploy to ignore all if .gitignore found in subdirectory other than project root

- src/views/ifsBrowser.js
- src/views/objectBrowser.js
This PR will allow searching a source file without using a filter. When the `Search Source File` command is run from the command palette, the user will be prompted for the source file (and members) to search in.
The PR was created as a solution to issue #927.
In addition the `Search Directory` command was changed to allow the user to specify the directory to search when run from command palette.
> Search without filter

- src/api/Search.ts
This PR is an attempt to solve the problem discussed in issue #1082 - by changing the regular expression used to remove the ASP name and/or /QSYS.LIB/ from the front of the paths returned by the grep search.
It was tested using ASP setting on the users job description, not the ASP setting in the connection.
I am not sure what is the idea behind the ASP setting in the connection configuration or the retrieval of ASP's using SQL ASP_INFO...?
> Fix regexp pattern to remove ASP and/or QSYS.LIB from path

- src/filesystems/qsys/complex/content.js
- src/languages/general/SEUColors.ts
This PR will add support for more SEU colours. Some colours were for some reason not implemented, but the PR will correct this.
The underlining has also been corrected for some colours, and the colour used for underline is now the same as for the foreground text.
One particular challenge was green, underline, reversed image, which uses hex 25. This hex value is the equivalent of ASCII / UTF8 hex 0A - linefeed! So my solution was to have SQL convert the hex 25 to hex 2F, which is converted to hex 07 in ASCII / UTF8, when reading the source member, and vice versa when saving the member, and map the text decorator for green, underline, reversed image to hex 07. Since this is done in SQL and only active when source dates are enabled, the conversion is not done when source dates are not …
> Support additional SEU colours

- package.json
The command titles were not uniform and did not conform to the VS Code standard of title casing. This PR will fix this.
It will also
- remove the word `user` from the `Change user library list` command - reflects the `CHGLIBL` command
- remove the word `new` from the `Create new library` command - it's not possible to create an old library! :laughing:
> Make command titles conform to VS Code standard

- package-lock.json
- package.json
- src/api/Instance.ts
- src/api/Storage.ts
- src/extension.ts
- src/instantiate.ts
- src/views/ConnectionBrowser.ts
Enabled command `code-for-ibmi.connectPrevious` to actually connects to the IBM i previously connected to.
The last connection name is stored using the new `GlobalStorage` class. The `Storage` class is now an abstraction and the previous `Storage` class has been renamed to `ConnectionStorage`.
Connecting to the previous connection can be achieved by:
- Executing the command from the Command Palette
- Clicking on the "Connect to previous" button in the Connection browser menu
If no previous connection exists in `GlobalStorage` or if the previous connection is deleted, the button/command palette action won't be available.
> Implemented Connect to Previous connection

- package.json
Only show debug button for certain sources.
Issue: https://github.com/halcyon-tech/vscode-ibmi/issues/1062
> Fix: Only show debug button for certain sources

- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/instantiate.ts
> Gracefully disconnect

- src/webviews/filters/index.js
Fixed issue https://github.com/halcyon-tech/vscode-ibmi/issues/1138
Filter's `memberType` field was not assigned when copying to a new filter.
> Fixed filter's member type field not duplicated when copying

- src/views/libraryListView.js
This PR will fix validation of the library list. Previously it would stop after first invalid library, but this fix will find all the invalid libraries in the list - as was intended...
> Fix library list validation: find all invalid libraries

- src/filesystems/qsys/QSysFs.ts
When source date support is disabled, QSysFS writeFile method will not wait for the upload to complete before returning.
> Missing await on QSysFS basic write

- src/api/CustomUI.ts
The `name` attribute was missing on the UI `select` fields. It prevented value from being retrieved.
This PR fixes
- https://github.com/halcyon-tech/vscode-ibmi/issues/1166
- https://github.com/halcyon-tech/vscode-ibmi/issues/1167
- Every webview with a `select` input
> Fixed missing name attribute on select

- src/api/CompileTools.ts
- src/api/Search.ts
- src/filesystems/qsys/QSysFs.ts
- src/typings.ts
- src/views/objectBrowser.js
- src/views/searchView.ts
* Solves issue that filter query parameter was causing diagnostics to no longer match up (#1173)
* Fixes consistent use of readonly flag where `filter` had a second implication (go and find out if this filter is readonly or not)
* No longer allow readonly sources/objects to have Actions run against them
> Fix use of filter parameter on Uris

- src/filesystems/qsys/extendedContent.ts
SQL `TRANSLATE` is expensive when inserting a lot of data. This was very visible when working with large files. Translate is only required for source colour support, so therefore the save should only use translate when source colour is enabled.
I don't use source colours and this has sped up the save process significantly.
> Source date save now checks before using `TRANSLATE` scalar

- src/filesystems/qsys/QSysFs.ts
Seems that `query` always return string values, so `false` as a string is a truthy value.
Solves #1185.
> Ensure that readonly is boolean

- src/api/IBMi.ts
- src/instantiate.ts
- Fixed disconnection failing when connection was dropped unexpectedly
- Allow to try reconnecting at will; if re-connecting fails, the following modal dialog will show up:
- Allow to force disconnection when dirty editors are still opened
- Keep dirty editors opened when disconnecting forcefully
> Fixed dropped connection handling + allow force disconnection

- src/filesystems/ifs.js
* Adds missing methods to IFS file system provider that are now required in 1.77.0
* Copied directory from `QSysFs.ts` which does the exact same thing
> Fix for 1.77.0: Include unused methods in IFS FS provider

- src/api/CustomUI.ts
- src/webviews/actions/index.js
- src/webviews/variables/index.js
This PR will keep track of opened webviews and prevent multiple occurrences of the same webview (i.e. with the same title) to be opened.
If a webview is already opened and a request to open it again is issued, the opened webview will be revealed.
> Do not allow the same webview to be opened multiple times

- src/api/IBMiContent.ts
address issue #599.  Fixes SQL Statement if comments start anywhere besides position 0 in a line.
Tested:
> runSQL API support comments not starting in position 0 of a line

- package.json
- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/api/debug/index.ts
- src/filesystems/ifs.js
- src/filesystems/qsys/QSysFs.ts
- src/filesystems/qsys/sourceDateHandler.ts
- src/instantiate.ts
- src/typings.ts
- src/views/objectBrowser.js
The member URI used to open the created/copied was wrong and prevented it from being opened right after its creation.
The commands now use `vscode.open` and `getMemberUri` to open the new member.
Member copy/creation process has been enhanced:
- Target name/path gets validated by vscode `showInput` API
- User can choose to retry in case of failure
- The process runs with a progress notification
> Fixed member opening after create/copy operations

- src/api/IBMi.ts
- src/instantiate.ts
* This exposes one of the last major APIs, `runCommand`. We have already exposed our SQL API and CustomUI API, so this one was missing.
* Along with adding this API, I have removed the old ways of invoking these APIs - which is what we used prior to our export API.
* The `code-for-ibmi.openErrors` will now allow a parameter so users can call this an API dynamically
* Our [extending doc](https://halcyon-tech.github.io/docs/#/pages/api/extending) really needs to some work, so I am going to work on that if it gets merged.
This could be a fairly breaking change, but one I'm willing to take for a big release like 2.0.0.
> Remove outdated command APIs and expose `runCommand`

- package.json
- src/extension.ts
- src/testing/connection.ts
- src/testing/index.ts
- src/testing/testCasesTree.ts
Added a Treeview to follow and check tests progress and results.
The tree refreshes after each test execution.
Colors and icons vary depending on the test results.
When all tests passed:
When some tests failed:
Hovering over a failed test will show the failed assertion in the tooltip:
> Proposal: test cases UI

- src/testing/index.ts
- src/testing/testCasesTree.ts
- webpack.config.js
I found that I wanted to re-run failed tests so I could debug, so I added that.
* Tests are clickable when not  in the `running` state
* Regarding the command, it is not required to add anything to `package.json` here since we aren't making it accessible from any UI elements (including the command palette)
* Test hover content is now in markdown to make it just that little easier to read
> Ability to rerun tests, markdown results

- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/testing/content.ts
- src/testing/index.ts
* Tests for many methods in IBMiContent
* Fixes for:
* Record length now corrected for member list when SQL disabled
* `runSQL` now returns a `sqlstate` property (this is non-breaking)
> Tests for IBMiContent

- package.json
- src/api/Configuration.ts
- src/api/IBMi.ts
- src/api/Storage.ts
- src/views/ConnectionBrowser.ts
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
This PR will add a `Quick Connect` setting in the connection configuration to speed up connecting to the system:
When selected, the following server settings are taken from the previous connection to the system:
- bad data areas
- all remote features
- ASP info
- CCSID
- encoding values for #@$
These values are stored in connection storage on each connection to the system. So if no previous connection has been done, even though the `Quick Connect` is checked, all settings will be retrieved from the server and stored in the connection configuration to be used on the next connection.
This setting is active by default. The user can disable it permanently in the configuration, or the user can reload all settings from server into cache by right-clicking on the connection and select `Connect …
> Add Quick Connect

- src/instantiate.ts
- src/testing/connection.ts
- src/testing/content.ts
In a recent PR (#1158), I added `instance.getConnection().runCommand` and removed `code-for-ibmi.runCommand` from our provided commands. `runCommand` is vital to a couple of other extensions, and removing it without giving time to use the new API will cause extensions (like RPGLE and Db2 for i) will just stop working until they start using the new API.
This PR still releases the new API, will let other extensions continue to work, and give time to those maintainers to upgrade to the export APIs instead.
> Add legacy API commands back

- src/api/IBMiContent.ts
This PR will fix running the `stat` command on directories, which are empty or has special characters in the name, e.g. `$`.
The error was introduced in PR #1153, and caused the following error in VS Code:
> Fix stat on empty or specially named directories

- src/api/local/deployment.ts
- src/typings.ts
- Fix https://github.com/halcyon-tech/vscode-ibmi/issues/1262
- Offer to set a deploy directory when trying to deploy a project with no deployment  target
The `FileSystemWatcher` used to watch files changed in the workspace would register each change globally, instead of registering them by workspace folder. Changes are now stored by workspace folders.
> Fix Changed deployment method for multi-folders workspaces

- package.json
- src/filesystems/ifsFs.ts
- src/filesystems/qsys/QSysFs.ts
- src/views/ConnectionBrowser.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1267
Opening VSCode with `member://` or `streamfile://` documents left opened on closing will now force the extension to reconnect before reading the files.
The process will try to reconnect once and throw an error if it fails to reconnect.
> Reconnect to previous IBM i when FS reopens

- src/api/CompileTools.ts
- src/api/Tools.ts
- src/api/local/actions.ts
- src/schemas/LocalLanguageActions.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1261
The post download directories creation would crash, on Windows at least, with the following error:
```
Error (FileSystemError): Unable to resolve filesystem provider with relative file path 'c:\Temp\bob-recursive-example\.logs'
```
The creation process has been fixed and the following rules now apply:
- Post download directories are created if they don't exist
- Post download directories are deleted and created if they exist
- If the post download target exists in the workspace but is not a directory, a warning will ask if it should be deleted first
Also, `.evfevent` has been added as a post download folder for BOB's default actions (it may be parsed in the future).
> Fix post download directories creation

- package-lock.json
- package.json
- src/api/IBMi.ts
- src/api/local/deployment.ts
Files to be deployed are put in a tarball (.tar archive) before being sent.
The benefits are:
- Faster deployment times, especially when deploying a lot of files
- Simpler deployment process (directory creations is handled by the `tar` command)
- File attributes and access permissions are kept during the transfer (if deploying from a POSIX os; not applicable for Windows)
Will fix https://github.com/halcyon-tech/vscode-ibmi/issues/1026
> Use tarball to transfer files to deploy

- src/api/IBMi.ts
This PR will add a check for additional user content in the output from shell commands during connection, thus eliminating issues like #1255 and others with similar root cause.
If the user has a shell start script with `echo` or any other command, that sends output to stdout, then Code will not be able to interpret the output correctly, and the user will see some mysterious errors - see #1255. This new check will ensure no such additional user content is present, else an error will be issued and the connection attempt aborted.
> Add check for additional user content in shell output

- .vscodeignore
Updated .vscodeignore to exclude the following folders/files from the vsix build:
- `src/`
- `types/`
- `tsconfig.json`
This reduces the size of the vsix from ~400KB to ~200KB.
> Exclude src/, types/ and tsconfig.json from vsix

- src/api/IBMi.ts
- src/api/Storage.ts
This PR will fix the Quick Connect test for remote features.
When any remote features were missing on the system and had the value `undefined`, the cached values for remote features did not include the key for the missing feature. And then the test for matching keys did not work, and the remote features were always searched for on the system.
In this PR the keys for all remote features are cached in addition to the values, and the test has been changed to be on the cached keys and not keys in the cached remote features.
This way any future change to the remote features will still initiate a search on the system, while Quick Connect will work correctly when there is no change to the remote features.
The error was discovered after the `tar` feature was added in #1265 by @sebjulliand - it …
> Fix Quick Connect with undefined values

- src/instantiate.ts
The following error would show up if the extension needed to load the CL API:
`rejected promise not handled within 1 second: Error: Cannot find module './languages/clle/clAPI'`.
This PR fixes the import and the error.
> Fix clAPI module not found error

- src/api/local/env.ts
Change to use `fsPath` instead of `path` so check for `.env` file works on Windows
> Fix check for existence of `.env` file

- package.json
- src/api/CompileTools.ts
- src/api/IBMiContent.ts
- src/api/Terminal.ts
- src/instantiate.ts
This PR adds an `Open PASE terminal here` action in the IFS browser.
It can be run on any element. It will open a PASE terminal and change the current directory for the one selected in the browser. If it's run on a file, it will open on the file's parent directory.
If a PASE terminal is already open, it will reuse it instead of creating a new one.
The PR also makes terminals opened by Code for IBM i to be closed when disconnecting.
> New "Open terminal here" action

- src/extension.ts
Allow users to reload server settings via `connectDirect`
> Ability to reload server settings via connectDirect

- src/extension.ts
- src/views/helpView.ts
This PR will add the versions of this extension, VS Code and the platform running it to the issue details, when a user created an issue on GitHub from the Help panel.
This could be the start of having more debug information available. We often ask the same questions to users creating issues, and it would be time-saving to have this information available from the beginning.
What else comes to mind? I think of the following:
- the help view should maybe always be present and not just when connected - the user may need help or guidance before connecting to any system.
- the last errors shown are from the connection time. These should always be updated, so we have the errors from the situation when the user is having trouble.
> feat: Add versions and platform to issue

- src/api/IBMiContent.ts
- src/views/ifsBrowser.js
- src/views/objectBrowser.js
This PR will change the member change date and time to show LAST_SOURCE_UPDATE_TIMESTAMP instead of LAST_CHANGE_TIMESTAMP when using SQL - this is the same value as shown when SQL is disabled.
Times are now shown in ISO format `YYYY-MM-DD HH:MM:SS`.
Member timestamps have no timestamp, but the streamfile timestamp will consider the timezone.
> Fix member hover change timestamp when using SQL

- package.json
- src/extension.ts
- src/views/helpView.ts
- The `Help & Support` view is now always displayed (not only when connected)
- Issue template's content depends on the extension connection status
- The template now organize information in collapsed sections to improve readability
- Some data are now listed in tables to improve readability
- Platform's architecture
- List of active extensions
- IBM i OS version and TR number
- Shell `env` output
> Issue reporting enhancements

- README.md
- src/views/helpView.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1320
Fixed the `Getting Started` from the `Help and Support` view pointing to a wrong URL.
Fixed the `README` links as well.
> Fixed Getting Started URL

- src/api/local/deployment.ts
Renamed `ignore` import to `createIgnore` for more clarity.
> Disambiguate Ignore/ignore imports

- src/api/IBMiContent.ts
- src/testing/connection.ts
- src/testing/content.ts
- src/views/ifsBrowser.js
This PR will fix the display of non-existing and empty directories in the IFS browser. Now errors will be caught for `stat` output:
And the list of files will only be generated when the directory has content (`stdout` is not blank).
The PR was created to fix issue #1325.
Additional tests and fixes:
- Test for getting non-existing IFS file
- Fix test getFileList for QSYS.LIB (path was not valid, owner was added)
- Fix test of runCommand API
- Allow lowercase member and extension in getMemberList (previously only library and sourcefile were uppercased)
- Fix test of getMemberList (SQL, no filter) (number of members in QSYSINC/MIH varied across releases)
- Pad member dates and times with zeros (non-SQL) (made timestamp creation fail)
- Test for valid directory when creating IFS shortcut (as …
> Fix display of empty and non-existing directories

- package.json
- src/views/ifsBrowser.js
This PR will add a right-click option `Copy Path` to the IFS browser to copy the selected path to the clipboard.
> feat: Add Copy Path to IFS browser

- src/api/IBMiContent.ts
- src/testing/content.ts
- src/views/ifsBrowser.js
`IBMiContent.getFileList` was using `vscode.window.showErrorMessage` to display non fatal error occurring when listing files.
With this PR, the handling of those error is now delegated to an optional callback received in parameter. If there is no callback, the errors are sent to the console.
> Externalized files listing errors

- src/api/IBMiContent.ts
- src/instantiate.ts
- src/views/objectBrowser.js
This PR addresses what's been discussed here: https://github.com/orgs/halcyon-tech/discussions/1331
- Source file write access is now checked when it's expanded in the Object Browser. If it cannot be written to, all members will be opened in read-only mode (and a lock will be shown next to the members).
- Write access is also checked when opening a member using the `Go to File` command. The member is open in read-only mode if its source file cannot be written to.
Checking the write access while saving was not implemented since it would show the misleading "Failed to save" dialog.
> Check if member can be written before edition

- src/api/IBMiContent.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1348
When using `stat` to list a folder's content, the `cd` command run before failed if the target path had whitespaces. Puting quotes around the path fixes the issue.
> Fixed cd failing when path has whitespaces

- src/instantiate.ts
When an IBM i PASE terminal has been started previously and exited, the Open Terminal Here function does not work anymore because it selects the exited terminal.
This PR changes the behavior for Open Terminal Here to always start a new IBM i PASE terminal.
It is still possible to use a path in an existing terminal by selecting `Copy Path` and switch to the existing terminal and enter `cd` and paste the path into the terminal.
> Always start a new terminal for Open Terminal Here

- src/views/helpView.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1364
`Report Issue` would crash if the user was not authorized to `WRKPTFGRP` (like many of us on PUB400).
The related SQL query is now surround by `try/catch` to avoid it from crashing the whole process. If the user is not authorized, we'll try to read the `QUSRSYS/QSS1MRI` data area to get the OS version.
If it fails, `OS Version` and `TR level` will simply show `n/a`.
> Fix "Report issue" crashing when not authorized to WRKPTFGRP

- src/testing/content.ts
Create a test for calling `getFileList` to get files with special characters in their names.
This is to avoid errors like the one encountered in issue #1348.
> Add test for getFileList with special chars

- src/api/Tools.ts
- src/api/local/deployment.ts
- src/testing/connection.ts
- src/testing/deployment.ts
- src/testing/index.ts
- src/testing/testCasesTree.ts
This PR enhances the test framework.
- Added `Deploy all` test
- Added `Deploy compare` test
- Optional `before` method: if present, runs code before the test suite is executed and cancels the whole suite if it fails. The failure is displayed as a tooltip in the Tests browser.
- Optional `after` method: if present, runs unconditionally after the test suite is done running (even if cancelled)
- New `status` field
- Displays a spinning gear when the test suite is running
- Added a `duration` field, filled when the test case is done. The duration is displayed as a tooltip in the Tests browser.
- Added a `Collapse All` button
- Fixed error handling when the error thrown is not an `Error`
> Added before/after methods and test duration + deployment tests

- src/api/IBMi.ts
This PR will fix Quick Connect remote features test - `ls` was missing in the `remoteFeatures`, so all remote features were checked at each connection.
I have also created a note at `remoteApps` to remember adding any new name to `remoteFeatures`.
> Fix Quick Connect remoteFeatures

- CONTRIBUTING.md
- src/schemas/LocalLanguageActions.ts
For tools that support compiling from IFS stream files, the standard for CL and SQL based objects is to have the corresponding CL and SQL commands in stream files with the file extension that corresponds to the target object type.
i.e. `TABLE` objects have their DDL in a stream files with the extension `.table`
The complete set is described here https://ibm.github.io/ibmi-bob/#/welcome/features?id=support-sql-pseudo-source
This PR contributes the SQL file extensions to the  `Local Language Actions`.
> SQL extension support

- package.json
- Add `TGTCCSID(*JOB)` to defaults for CRTBNDRPG
- Add `TGTCCSID(*JOB)` to defaults for CRTBNDRPG w/ inputs
- Add `CVTCCSID(*JOB)` to defaults for CRTSQLRPG program
- Add `CVTCCSID(*JOB)` to defaults for CRTSQLRPG module
The specific RPG compilation commands changed complain on IFS source about the 1208 CCSID.
Added arguments to command string to convert source to the Job ccside.
* [n/a] updated relevant documentation
* [n/a ] **for feature PRs**: PR only includes one feature enhancement.
> Modify actions for RPG compile from IFS

- src/instantiate.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1398.
When running action without using `ctrl+e` and if the action is ran for the document currently being edited, the save/auto save feature was not triggered.
This PR fixes this behavior and save/auto save will always occur if the action is about to be run for the document being edited, regardless of the action's origin.
> Handle editor saving in any case when running actions

- package-lock.json
- package.json
- webpack.config.js
Finally upgraded node-ssh to 13.1. We failed to do it in the past because ssh2 (a sub dep) now builds binaries for the package, **but they are optional**. I have updated our webpack configuration to ignore the errors for those binary files.
See this issue for how someone else fixed it: https://github.com/mscdex/ssh2/issues/1213
> Upgrade node-ssh to 13.1

- src/filesystems/qsys/sourceDateHandler.ts
Improve when diff mode should refresh the gutter:
* refresh on delete
* refresh even after I use a space (this was a bug)
> Improvements to diff mode re-render handler

- CONTRIBUTING.md
- package.json
- src/views/objectBrowser.js
- Update when clause for commands in package.json to specify the view
- Remove `Move Object` command from libraries
- Update `Copy Object` command to use `CPYLIB`
> Update command contributions and use `CPYLIB` for `Copy Object` command

- src/filesystems/qsys/extendedContent.ts
* Attempts to insert new file into temporary table first. This is good because we can check the file will be saved without clearing out the original member first.
* Seems to have seriously improved the performance of member saving
> Use temp member to save new file

- src/api/Configuration.ts
Makes `diff` mode for source date editing the default for new system configurations.
> Set default source date mode to diff

- src/views/ifsBrowser.js
This PR will fix checking if the node is a directory when `Safe Delete Mode` is active:
Check for node context `directory` instead if node path ending in `/`.
> Fix checking for directory in safe delete mode

- package.json
- src/instantiate.ts
- src/views/objectBrowser.js
Added a Browse action in right-click menu of stream files and members.
This simple action was missing from these menus. The idea came from this discussion: https://github.com/orgs/halcyon-tech/discussions/1412
> Added "Browse" action on streamfiles and members

- src/api/local/deployment.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1405
For some reason (?) `tar` would give ownership of the deployed files to QSECOFR (always with `/usb/bin`'s `tar`, not on files with `/QOpensys`' tar).
Using the `-o` flag (i.e. `--no-same-owner`) fixes the issue and gives owner of every extracted files to the currently connected user.
> Use -o when extracting with tar to give ownership to current user

- src/api/IBMiContent.ts
- src/testing/content.ts
When testing the `getLibraryList` API, I noticed that for a library (with a text description of `*BLANK`), the `text` field was `''` when SQL is enabled, but `' '` when disabled. When SQL is disabled, the result which is parsed in `getTable` seems to have `' '` when there is no value. 
This PR makes the result consistent regardless of if SQL is enabled.
> Fix parsing of `getTable` result

- src/views/ifsBrowser.js
Based on a discussion had by a user who deleted root from VS Code (by accident?), we should no longer let users delete root since as the confirmation isn't enough.
> Prevent root being deleted from VS Code

- src/api/IBMi.ts
Fixes #1422.
Newer versions of node_ssh (and therefore ssh2) require us read the file and pass the buffer.
> Read in private key contents on connect

- src/api/local/deployment.ts
If you have a .gitignore in a subdirectory like .venv which might have entries like '*' 
the it will take precedence over the root
.ignore and nothing will be deployed.
> Do not use any .gitignore below project root

- src/instantiate.ts
Removes the Actions and Terminals items in place of tooltip buttons on the Settings item.
As much as I want this to, I am not expecting this to be merged due to how big of a UI change this is, but it sure is nice IMO.
> Remove status bar items for tooltip menu

- src/api/IBMi.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1465
This PR makes the variables replacement happen before the connection settings are actually used.
> Replace variables in settings before being used

- package.json
- src/filesystems/qsys/QSysFs.ts
- src/filesystems/qsys/sourceDateHandler.ts
Trying to cleanup some clutter in my VS Code instance. I never use this button so I'd like it gone so I made it configurable and on as default to fit how it works currently.
> Ability to hide or show the 'Date search' status bar item

- src/api/IBMi.ts
This PR will set the directory when checking for shell output.
Previously if the home directory did not exists, the check would fail (discovered while reviewing PR #1460)
> Fix directory for shell check

- .github/workflows/ci.yaml
Adds back the type generation and NPM publishing to the ci workflow.
**TO DO**: Add `NPM_TOKEN` secret to repo.
> Generate and publish typings through ci workflow

- src/api/IBMiContent.ts
- src/testing/content.ts
This will fix a bug that will allow the vscode-rpgle extension to resolve streamfiles with spaces in them (though... what crazy person would do that?!)
Tests are continuing to pass.
> Wrap paths to resolve with double quote

- CONTRIBUTING.md
- src/api/IBMi.ts
Fixes #1205 
Changes:
- Check if home directory exists but is not writeable
- Allow for automatic creation of home directory (after asking the user)
- Added a `console.log` message when creating the home directory (runs counter to PR checklist requirements)
- Remove guidance about giving the user a home directory via `CHGUSRPRF` as I believe it to be incorrect
* ~~[ ] updated relevant documentation~~ **N/A**
* ~~[ ] Remove any/all `console.log`s I added~~ **(See note above in change list)**
> Ability to create home directory

- src/api/IBMi.ts
People shouldn't do development with *ALLOBJ-type authority
> Add warning message if you're *ALLOBJ

- src/api/IBMi.ts
- src/api/Storage.ts
This PR was created to partially fix issue #1431 by validating the library list when connecting to a system.
If any libraries in the list does not exist, the user will be prompted to remove them from the list:
Library list validation is not done on Quick Connect.
> Validate library list when connecting

- src/api/errors/diagnostics.ts
- src/api/local/actions.ts
Fix change made in PR #1450 by adding `getEvfeventFiles` function.
> Add missing `getEvfeventFiles` function

- src/instantiate.ts
Whenever the user changes the first workspace folder or goes from a single-folder workspace to a multi-root workspace, the extension is restarted which is expected in VS Code as mentioned [here](https://github.com/Microsoft/vscode/issues/46048). However, right now this leaves Code4i's views as unusable (as shown below).
This seems to be because the value of the `code-for-ibmi:connected` context value is kept despite the extension restarting. Thus, this PR sets it to be false when we first activate the extension. Although this will require uses to have to reconnect, at least they can do this instead of having to restart the entire extension again.
> Initialize `code-for-ibmi:connected` context value when extension is activated

- package.json
- src/views/objectBrowser.js
Add `Create Quick Filter` action that allows users to quickly type a filter of the following format: `LIB*` or `LIB/OBJ/MBR.MBRTYPE (OBJTYPE)` where each parameter is optional except the library. For parameters which are not provided, the defaults will be used.
> Add `Create Quick Filter` action

- src/locale/index.ts
Additional conditional check to ensure the locale exists.
Fixes #1498
> Fix for attempting to use a locale that is not defined

- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/locale/ids/da.ts
- src/locale/ids/en.ts
- src/views/LibraryListView.ts
This PR will
- fix the problem in issue #1497 and allow ASP libraries in the library list validation when connecting.
- enhance validation when a library is added to the list
- show message when a library is removed from the list
- fix an error in library list validation, where the wrong library were removed, e.g. library ABC was removed if library ABCDEF did not exist
@sebjulliand Locale files has been changed with the following message id's:
```
LibraryListView.addToLibraryList.alreadyInList
LibraryListView.addToLibraryList.invalidLib
LibraryListView.addToLibraryList.addedLib
LibraryListView.addToLibraryList.removedLibs
LibraryListView.removeFromLibraryList.removedLib
```
Will you translate into French?
> Fix ASP and library list validation

- src/api/CompileTools.ts
Add the current host as a default variable to support the variable substitution documented for `buildCommand` and `compileCommand` in `iproj.json`. For references: https://ibm.github.io/vscode-ibmi-projectexplorer/#/pages/ibm-i-projects/iproj-json?id=buildcommand
> Add the current host as a default variable

- src/api/CompileTools.ts
- src/instantiate.ts
- src/languages/clle/clRunner.ts
Since `CompileTools.runAction` now uses task, it returns right after the task is created and started.
This PR makes it wait for the actual end of the action before returning and also lets the `code-for-ibmi.runAction` command returns the result of the action as a `boolean`.
> Wait actual end of CompileTools.runAction

- package.json
- src/api/CompileTools.ts
- src/api/Configuration.ts
- src/api/CustomUI.ts
- src/webviews/settings/index.ts
Adds a new connection setting so the user can control what UX they want when running an Action.
1. Set to 'Show Action'
* Expect only the task to show as the Action is started
2. Set to 'Show Problems'
* Expect only the Problems view to show when the Action has been run
3. Set to 'None'
* Expect no views to be shown
> Control UI UX for running Actions

- src/views/objectBrowser.ts
Added a missing call to `t()` in the Object Browser to fix this translation:
> Missing call to translation function

- .github/workflows/ci.yaml
This PR adds two actions to the release process:
- It automatically change set the version number in the extension's `package.json` and in the types' `package.json`, based on the release name.
- It commits and push this change on the master branch
This would allow contributors to create a release without the need to create a PR for bumping the versions.
It also ensures that both the extension and the types version are always aligned when publishing.
> Automatically bump versions on release

- src/typings.ts
The `ProviderResult` type imported in the typings was imported from the Git API types instead of `vscode`'s.
> Fixed ProviderResult import in typings

- src/api/IBMi.ts
- src/extension.ts
- src/sandbox.ts
- src/typings.ts
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
- Use the correct field used by node-ssh Config object
- Added a method called on activation to fix existing configurations (can be removed in the future)
- Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1542
The private key file content was loaded into the `privateKey` field, which is not wrong, but it caused an issue when the `ConnectionData` object was reused while reconnecting a dropped connection.
This PR renames `ConnectionData` `privateKey` to `privateKeyPath` which is an actual field used by node-ssh when connecting. This way we use the correct field for the job and leave it up to node-ssh to read the file's content, too.
A small migration method is called when the extension activates to update the existing configurations.
> Renamed connection's privateKey to privateKeyPath

- src/extension.ts
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
This PR makes sure that `privateKeyPath` is always `undefined` and never `''` in the login settings.
It completely removes `privateKey` once and for all.
It removes some fields from the login page who could have made their way in the settings (like `buttons`).
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1550
> Fix and cleanup login settings

- src/views/objectBrowser.ts
Fixes https://github.com/halcyon-tech/vscode-ibmi/issues/1565
The object type test made in the `code-for-ibmi.copyObject` action was not changed after the Object Browser was converted to TypeScript. This PR fixes the test to compare the selected object's type with `*lib`.
> Fixed copyObject crashing when copying library

- package.json
- src/views/objectBrowser.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1555
The `code-for-ibmi.refreshObjectBrowser` used to accept no parameter; after converting the Object Browser to TypeScript, that command was changed to accept a TreeItem in parameter, to allow finer refreshes. It turns out that the browsers selected item was always passed onto the command when the `Refresh` inline button was clicked.
This PR revert that change so the command behave as it used to (i.e. clicking on `Refresh` refreshes the entire browser.
It also adds a new `code-for-ibmi.refreshObjectBrowserItem` command that is dedicated to refreshing the browser selected item. A `Refresh` action has been added on every browser's item to enable refresh at every level.
> Split Object browser's Refresh in two separate actions

- .github/pull_request_template.md
- .github/workflows/pr.yaml
- CONTRIBUTING.md
- LICENSE
- README.md
- package.json
- src/api/IBMi.ts
- src/views/helpView.ts
- types/package.json
> Update helpView.ts for changes to organization name

- src/instantiate.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1584
This PR removes the query part of the URI shown when prompting for a source member to compare to.
> Remove URI query part when prompting for member comparison

- CONTRIBUTING.md
- src/api/Terminal.ts
In **Terminal.ts**, filter out the extra **echo** without printing it. Now the PASE terminal welcome message looks clearer.
No doc points in https://codefori.github.io/docs/#/ need to be updated.
bz.
> Remove extra echo line in the PASE terminal head

- src/api/IBMi.ts
Change error text when 65535. This aligns better with the Db2 for i extension, which works even if the QCCSID is 65535.
> Change invalid QCCSID text

- package.json
- src/api/errors/diagnostics.ts
Since it wasn't possible to move diagnostics as documents change, we've added a piece of code that will clear the error if the line it is on edited. This suggested came from a user.
> Feature to clear error on line edit

- CONTRIBUTING.md
- src/api/debug/index.ts
Make sure the submit job command is called using MSGQ(*USRPRF) when starting a debug session.
Closes #1600
> Fix for issue 1600: Debug session does not start if the command default have been changed to MSGQ(*WRKSTN) for the SBMJOB command

- src/views/objectBrowser.ts
Sorting in the Object Browser was not working properly because:
- Nodes' `refresh` method was not calling the correct command
- The `sortBy` method at member level was not bound correctly
> Fixed sort action in Object Browser

- package-lock.json
- package.json
- src/api/debug/index.ts
- src/webviews/settings/index.ts
* Adds `DEBUG_MANAGED` variable, and when `true` will:
1. Hide the certificate UI in the connection settings
2. Control secure mode based on if `DEBUG_CA_PATH` environment variable is set
3. Hide 'setup debug' commands
4. Hide debug setup walkthrough (PR in a separate repo)
> Environment variable to manage debug settings

- src/instantiate.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1622
The `object` URI scheme was not part of the test allowing to call `CompileTools.runAction` in the `runAction` command.
> Fixed runAction command not working on objects

- src/extension.ts
Adds new parameter to the `connectDirect` API to store the password into the keystore. This is so the debugger doesn't prompt the user awhen using the API to connect.
> Save password during connection via API

- src/api/debug/index.ts
Set the default debug library to the CURLIB environment variable when debugging from local source.
> Set the debug current library when debugging locally

- src/api/CompileTools.ts
Because `BRANCH` was before `BRANCHLIB`, I was getting the incorrect value in `BRANCHLIB` as `&BRANCHLIB` was evaluating to `some/random/branchLIB`
> Fix variable assignment order in CompileTools.ts

- src/typings.ts
This will allow a `privateKey` property on `ConnectionData`, which allows the content of the private key to be passed in, instead of solely just the path to the key.
No UI changes needed as this is a requirement for the connection API.
> Additional privateKey prop to allow private key strings

- src/api/IBMiContent.ts
This fixes an issue that can happen when `downloadMemberContent` is called to open a member located on `*SYSBAS` and an iASP is specified in the Connection Settings (i.e. `config.sourceASP`).
When `config.sourceASP` is set, `downloadMemberContent` will always assume the member content to fetch is located on that IASP. If the member is actually on `*SYSBAS`, it can never be read.
This PR makes `downloadMemberContent` tries twice to fetch a member if an IASP is set in the settings:
- First it assumes the member is on the IASP (as it used to)
- If not found, it will try again without the IASP in the path
- If still not found, then it crashes
> Look for member on SYSBAS if config.sourceASP is set

- src/api/CompileTools.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1586
On Windows, there is sometimes a case difference in the path's drive letter. For example:
In my case, I could reproduce this by having two workspace folders in my workspace folders in my workspace and running a local action after opening a file from the Search results (like described in https://github.com/codefori/vscode-ibmi/issues/1586).
This PR simply checks the target platform and run the `path.win32.relative` function to get the relative path for local actions if running on Windows.
> Use OS dependant function to get relative path

- src/locale/ids/da.ts
- src/locale/ids/en.ts
- src/locale/ids/fr.ts
- src/views/ifsBrowser.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1631
When running the `Delete Object` action from the IFS browser, if the target was the current directory (i.e. `config.homeDirectory`)  the command would fail and show a success message.
This PR fixes this issue by:
To reproduce the initial issue:
- Create a directory
- Set it as the Working Directory (right click action from the IFS Browser)
- Try to delete it
> Fix deletion current directory and check error

- src/api/IBMiContent.ts
This PR will fix the old error of `stat` complaining `cannot stat '.*'` by adding a filter for it - like the already filtered error `cannot stat '*'`.
> Ignore stat error when no hidden files in directory

- package.json
Fixes https://github.com/codefori/vscode-ibmi/issues/1662
This makes the Copy member action available on protected filter's members.
> Allow copy member from protected filter

- src/api/IBMiContent.ts
Fixes issue where member resolves with dollar signs in the name (which sadly is very common) was not working because `$` is a special character in the shell.
Unit tests for `memberResolve` are continung to pass.
> Add code to escape member names when doing resolve

- .github/workflows/ci.yaml
- .github/workflows/pr.yaml
This PR address #1156 .
Renamed to use updated name for the vsce tool according to [VS Code November 2022 update](https://code.visualstudio.com/updates/v1_74#_renaming-of-vsce-to-vscodevsce)
I'm not sure how to test this since it is on the publishing side but hopefully its a good start.
> fix use of old vsce command

- src/api/CompileTools.ts
- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/testing/content.ts
- src/testing/tools.ts
- src/views/LibraryListView.ts
This PR will fix the error described in issue #1672.
It will also fix errors in other library list commands:
- show an error when changing current library, if the new current library name starts with `#`
- don't allow non-existing libraries with name starting with `#` when changing the library list
> Sanitize library names before running liblist command

- src/api/debug/certificates.ts
- src/api/debug/index.ts
- src/api/debug/server.ts
- src/webviews/settings/index.ts
I realised today while helping a user out that even after VS Code configures the certificates for both the server and client, it never imports the client certificates automatically from the server.
This change will now not only do that, but also improves the wording so that the server certificates cannot be overridden when they have already been created (as it only needs to happen once for the entire system)
Also, this PR adds a warning when trying to debug securely when connecting to the IBM i with an IP address. A hostname is basically required for secure debugging right now because of the way the certificates are setup. This will hopefully be resolved in a future PR.
> Improvement to debug config UX to download client certificates

- src/instantiate.ts
This pull request is a squashed version of PR #1242 and must be used instead to make a cleaner git history.
The original author @sebCIL is kept on the commit.
> feat(Go to file): Autotype suggestions typing path

- src/api/local/LocalLanguageActions.ts
Adds three new default actions:
1. Action to create a service program from source (binder source)
2. Build current source with Source Orbit
3. Build all source with Source Orbit
> New addtional default actions

- CONTRIBUTING.md
- src/api/debug/certificates.ts
Use both hostname and ip address when creating the debug service certificate, so users can use either one of them for connection.
> Use both hostname and ip address for debug service certificate

- src/instantiate.ts
This PR will fix some issue with the new search function in Go To File:
- The list label sort is disabled, since the list is already sorted when sent to UI.
- A progress bar will be shown when searching the server.
- The list is now more dense by showing text as description instead of detail.
- The labels are now shown correctly
- The list is now correctly changed to cached files when the value is cleared.
- The `Clear list` will always be shown, now with a separator line above and an icon in front.
> Fix goto file quickpick

- package.json
- src/views/ifsBrowser.ts
This PR changes the IFS browser behavior in the following ways:
- When copying or moving an object, only the object name will be selected in the prompt for faster entering of new object name. Previously the full path was selected, which seemed a bit cumbersome.
- When creating a new directory or streamfile, the prompt is changed to not select the full path, but instead place the cursor after the path. This makes it faster to enter the name of the new directory or streamfile.
- A protection mechanism for vital IBM directories has been created. Now the following directories will not have the menu options for delete, copy or move:
- /
- /QOpenSys
- /QSYS.LIB
- /QDLS
- /QOPT
- /QNTC
- /QFileSvr.400
- /bin
- /dev
- /home
- /tmp
- /usr
- /var
The PR will make it faster working with objects in …
> IFS browser enhancements

- src/api/IBMiContent.ts
I noticed when vscode-rpgle tries to fetch rpglint.json from the QSYS file system, it was spamming if it was not found. This was due to some invalid retry logic where it would just get caught in a loop. This is also possibly related to the issue @pabloto found in #1704. You would see this, including for all missing includes, in the output log.
```
.: system "CPYTOSTMF FROMMBR('/QSYS.lib/LIAMA.lib/VSCODE.file/RPGLINT.mbr') TOSTMF('/tmp/vscodetemp-O_7cyB9KET') STMFOPT(*REPLACE) STMFCCSID(1208) DBFCCSID(*FILE)"
{
"code": 255,
"signal": null,
"stdout": "",
"stderr": "CPFA0A9: Object not found.  Object is /QSYS.lib/LIAMA.lib/VSCODE.file/RPGLINT.mbr.\nCPFA097: Object not copied.  Object is /QSYS.lib/LIAMA.lib/VSCODE.file/RPGLINT.mbr."
}
```
1. Check out to `master`
2. Have vscode-rpgle …
> Fix missing throw in downloadMemberContent

- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/filesystems/qsys/extendedContent.ts
- src/languages/clle/clApi.ts
- src/languages/clle/getnewlibl.ts
- src/testing/content.ts
- src/typings.ts
- src/views/objectBrowser.ts
This PR includes the following changes:
- It removes the deprecated methods `remoteCommand` and `paseCommand` from `IBMi`.
- It replaces the calls to these two methods with `sendCommand` or `runCommand` depending on the context.
- It adds a `noLibList` option to `runCommand`. If it is set to `true`, `runCommand` will not build the library list before running the command. This will fix issues we had with people seeing their members as read-only because of a faulty library list. Other command calls that should ignore the library list have been updated as well.
> Removed deprecated commands call and ignore library list

- src/api/CompileTools.ts
- src/api/local/deployTools.ts
Fix bug where remote CWD was not being set properly when running an Action against a file but were not deploying anything.
One Action test case was not passing before this.
> Always use deploy directory even when not deploying

- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/testing/content.ts
- src/typings.ts
Similar to opening files, `memberResolve` will now look in the user defined ASP to find a member. Additionally, the API can accept an ASP and will use that instead.
Also solves a bug with the `qualifyPath` which wasn't handling `QSYS` correctly.
> ASP support member lookup

- src/webviews/login/index.ts
Resolves https://github.com/codefori/vscode-ibmi/issues/1717
This PR organizes the new connection editor fields in tabs and adds the `Temporary library` and `Temporary IFS directory` fields.
> Added Temp dir/library input fields in new connection editor

- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/filesystems/qsys/extendedContent.ts
- src/languages/clle/clApi.ts
- src/languages/clle/getnewlibl.ts
- src/testing/action.ts
- src/views/objectBrowser.ts
Noticed when testing the new connection settings PR that when reloading or creating a new connection, I was always seeing this message about the old data area that we don't like, even though it didn't exist.
Previously, we relied on an API that was throwing an exception if the returned status code was not 0. We removed that API in place of an API that never crashes, but we didn't change the code around it. This is a pretty important fix and likely needs to be deployed ASAP.
Highest impact areas:
* Creating the connection
* Object Browser UI/UX
> Correct all places where it was expected runCommand to crash

- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/testing/action.ts
- src/testing/connection.ts
- src/typings.ts
- src/views/objectBrowser.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1739
This PR adds a method that will parse commands `stderr` into `IBMiMessages` to facilitate error analysis.
This helps checking what IBM i messages are returned after a command call and fixes some checking that only looked for the first returned message ID.
Also fixes a very weird bug that the core team have only been able to recreate on pub400:
```
qsh: 001-0019 Error found searching for command [[. No such path or directory.
```
This new test would fail without the one line change I made in CompileTools#runCommand.
> Fix CRTLIB error checking when connecting + other error checkings

- .github/workflows/ci.yaml
This PR enhances the release workflow by automating the version number change. This allows to make a new release without the need to create a PR to bump the version number in `package.json`.
It does the following:
1. Updates the version to match the release tag's
2. Packages once using vsce (through npx)
3. Publishes the package on the marketplace and openvsx
4. Attaches the vsix as a release asset
5. Commits the version number change, moves the release tags to this commit and pushes it all
6. Updates the version with a new prerelease version, bearing the `-dev` suffix
7. Commits and pushes the version update
It also uses Node 18 for building.
> Updated release workflow

- src/api/IBMiContent.ts
This PR fixes the `getObjectList` method that showed a confusing error when trying to list objects from a non existing library:
Now the method will first check if the library exist before carrying on and show a relevant error message if it doesn't:
- Create filter for a library that doesn't exist
- Expand the filter
- Witness the error messages
> Check if a library exists before listing its content

- src/instantiate.ts
This PR will fix issue #1732 by (re)adding the entered value to the list, thus allowing it to be selected (accepted).
This was a regression from the new member search in function Go To file.
Additional fixes are included:
- Validation of entered member reference - previously the user could enter any extension for the member, and the member would still open. Now there is a warning if the member does not exist or the member type is wrong.
- Search now works even if member and dot has been specified when entering '*'.
- Member type is shown in uppercase like the other parts in a list item.
- SQL statements and use of metadata columns are now consistent.
- The Go To file dialog are kept open when the list is cleared.
- Validation of entered streamfile before open - keeping the list available …
> Fix error opening a specific member reference in Go To File

- package.json
- src/api/Storage.ts
- src/instantiate.ts
This PR will show the recently opened files in the Go To file list, with the last opened file first in the list and a button to clear the list of recently opened files:
This makes it very easy to reopen a previously edited/browsed file. :boom: 
A configuration setting has also been added to control the number of recently opened files in the list:
> Show recently opened files :boom: 

- src/api/IBMiContent.ts
This PR resolves issue #1762 by escaping the path before testing access rights for the streamfile.
> Escape path when testing streamfile for access rights

- src/api/IBMiContent.ts
Show a warning message when the uploadMemberContent function gets a CPIA083 to tell the user the member content was saved but there were truncated lines.
> Fix #1172 - No warning of truncated lines when saving to source member 

- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/instantiate.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1765
The path parsing was incorrect when opening a member located on an iASP. Since this kind of path begins with the iASP, it would return the iASP name as being the library.
This PR adds a method in `Tools` that will correctly parse the path in any case.
> Fix path splitting when opening a member on an IASP

- src/extension.ts
- src/instantiate.ts
- src/sandbox.ts
- src/views/ConnectionBrowser.ts
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
There is a bug with starting the debugger if the user once used a password, but is now using a private key, as the user would never be prompted for the correct password when debugging.
> Delete password when private key is used

- src/api/errors/diagnostics.ts
There was an issue where the deploy path could be inside of an ASP without it being on the path explicitly.
For example, if the deploy path was: `/home/user/abc`, the compiler can possibly return `/MYASP/home/user/abc` in the `evfevent` logs.
> Take in account for possible ASP in compile path

- CONTRIBUTING.md
- src/api/Configuration.ts
When parameters variable is undefined it is generating an error when trying to reference parameters.name. Added check to ensure parameters.name is defined before updating the connection information. There is also no need to update the connection information if parameters.name is undefined.
> Fix error when referencing undefined parameters variable

- package-lock.json
- package.json
- src/api/Configuration.ts
- src/api/Filter.ts
- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/sandbox.ts
- src/testing/content.ts
- src/testing/filter.ts
- src/testing/index.ts
- src/typings.ts
- src/views/objectBrowser.ts
- src/webviews/filters/index.ts
Resolves https://github.com/codefori/vscode-ibmi/issues/1779
This PR enhances the Object browser filters by adding support for more advanced filtering options.
Every field of a filter now supports filtering:
- Libraries
- Objects
- Object types
- Members
- Member types
Multiple libraries can now be browsed with a single filter.
When source files are found in the list (if `Object Types` list includes `*SRCPF` or `*ALL`), they can be browsed as well - they are not treated as simple Objects anymore:
The filtering type is defined for every field of the filter.
- **Simple**: each filed will support multiple comma-separated values that can contain multiple `*` as wildcard. Example: `QSYS*, *TEST, *SAMPLE*, A*B*C, YAY`
- **Regex**: each field will support a single RegEx for filtering values
This …
> Enhance Object Browser filter's Object field

- package.json
Fixes #1556. Years ago, we had the option to deploy from local to source members. We took that out years ago too, but this context option was left in.
> Removes deploy option from object browser

- src/testing/action.ts
Existing tests were missing props added by previous API changes.
> Add missing props to explicit check in tests

- src/api/IBMi.ts
This PR makes the connection failure messages more explicit, depending on the error.
There are three error cases for which we provide an explicit message:
- Host is unreachable
- Port is unreachable
- Credentials are wrong
If the error case cannot be determined from the error returned by SSH, then the error is displayed as it used to be.
Example of the three possible messages:
> Display more explicit error message when connection fails

- src/api/IBMiContent.ts
- src/testing/content.ts
* Adds `member` property to `checkObject` API, allowing us to check if members exist
* Created a new `toCl` static method to generate the formatted CL commands. I'd like to move towards using this instead of hardcoding CL strings everywhere.
* Tests for `checkObject` API uses
> `checkObject` to support checking member

- src/api/IBMiContent.ts
- src/filesystems/ifsFs.ts
I noticed our IFS filesystem wasn't forcing everything as UTF8, which meant we couldn't open up non UTF8 files like PDFs, images, and spreadsheets that reside in the IFS. 
I have added created new raw APIs that we should use instead, and made the previous download/write APIs call the raw API and convert to UTF8 to keep the previous functionality.
Test cases are continuing to pass.
> Correctly read files from the IFS

- package.json
This PR will make subtle changes to the wording of context menu items in the IFS browser, to be more compliant to the VS Code File Explorer and more concise.
IFS shortcut - before and after:
IFS directory - before and after:
Also, in Object browser the refresh button text has been changed from "Refresh Objects Browser" to simply "Refresh".
> Fix context menu items wording in IFS browser

- src/webviews/settings/index.ts
This PR will move the setting `Sort IFS shortcuts automatically` to the correct tab `Features` - previously it was on the wrong tab `Temporary Data`.
> Move auto sort IFS shortcuts setting to Features tab

- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/api/local/deployment.ts
When removing temp directories in IFS, the `rm` would fail because it won't delete directories without the `-r` flag (recursive):
The `-r` flag has been added to the `rm` commands.
> Fix removing (temp) IFS directories

- src/api/IBMiContent.ts
Makes the member parameter on the `getTable` API optional, and assumes it to be the same as the table if not provided.
It used to work like this before, so not sure when this change was made.
> `getTable` API: Make member optional

- src/api/Tools.ts
- src/api/errors/diagnostics.ts
- src/instantiate.ts
* If you try and open a doucment, but already have it open in the oppisite edit mode, then you will get a warning and that open document will take focus.
* Clicking on an error should no longer open up a new document will try to use existing document URIs to inherit the readonly mode.
> Stop letting the same document be opened twice

- src/api/Filter.ts
- src/testing/filter.ts
- src/webviews/filters/index.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1847
Whitespaces in object filter's `library` and `object` fields were not trimmed, resulting in the filtering not working correctly.
> Trim whitespaces in object filter's library and object field

- src/locale/ids/da.ts
- src/locale/ids/en.ts
- src/locale/ids/fr.ts
- src/typings.ts
- src/views/ifsBrowser.ts
- src/views/objectBrowser.ts
This PR will allow dragging members from the Object browser into IFS directories in the IFS browser, to allow easy conversion of source members to streamfiles.
When the member is dropped into the directory, it will be copied using the CPYTOSTMF command. The streamfile will be named the member including extension in lowercase, and it will be UTF-8 encoded.
> Allow dragging members to IFS directories

- src/api/CompileTools.ts
In other places where we download directories, we have used a concurrency level of 5. I have also added that to post download of an Action.
> Add concurrency level to postDownloads

- src/api/IBMiContent.ts
This PR is an short, but effective addition to PR #1780 and will make *FILE object filters behave like filters for *SRCPF or *ALL, allow browsing of sourcefiles:
> Allow open members in object filters for *FILE

- src/api/Storage.ts
- src/languages/clle/clApi.ts
Solves a bug that was causing the CL installer message to always a appear after connecting for the first time, and choosing to ignore the installer.
Now, if you install on the second connect, you will no longer get the message.
> Store that CL component was installed after installing

- src/api/IBMiContent.ts
- src/views/objectBrowser.ts
This PR will fix the change from PR #1851 - the test in the PR was not correct.
Now we check for return code first, and only if error code 1 and messages and not messages
`CPF2869 (Empty member &3 in file &1 in library &2 is not copied.)` and
`CPF2817 (Copy command ended because of error.)`
do we ignore the errors and accept the outcome.
> Fix error copying empty member

- src/api/IBMiContent.ts
- src/locale/ids/da.ts
- src/locale/ids/en.ts
- src/locale/ids/fr.ts
- src/typings.ts
- src/views/objectBrowser.ts
This PR is a continuation of the tooltips changes - it adds a tooltip to objects in the object browser, when the object is not a source file:
> Add tooltip for objects in object browser

- package.json
- src/api/errors/diagnostics.ts
- src/api/errors/parser.ts
Adds the ability to keep diagnostics from other files around when running an Action.
> Add new configuration option to control clearing of diagnostics

- src/api/IBMiContent.ts
When SQL is disabled, loading the library list items take a significant amount of time because it runs `DSPOBJD OBJ(QSYS/*ALL)` to load the librarys' description.
This PR makes it run one `DSPOBJD` for each library which speeds up the loading of the Library List view.
The other possible fix for this is to disregard `config.enableSQL` entirely and always use `OBJECT_STATISTICS`.
> Speed up library list loading when SQL is disabled

- package.json
- src/locale/ids/da.ts
- src/locale/ids/en.ts
- src/locale/ids/fr.ts
- src/typings.ts
- src/views/LibraryListView.ts
- src/views/objectBrowser.ts
This PR adds a new `Set as current library` action, available from:
- Libraries in the `User Library List` view
- Single library Filters and .lib objects from the `Object Browser`
It adds the `Add to library list` action on:
- Single library Filters and .lib objects from the `Object Browser`
It also allows to run `Create source file` action on:
- Single library  Filters and .lib objects from the `Object Browser`
Finally, it removes `Add to library list...` from command palette when library list view is disabled
@chrjorgensen, I'll need your help for one translation 😄 
- Try `Add to library list` action from:
- A library from the `User Library List` view
- A filter from the `Object Browser`
- A .lib object from the `Object Browser`
- The `User Library List` view's title
- Try `Set as …
> 'Add to library list' and 'Set as current library' actions on browsers items

- package.json
This PR will stop Command Palette from showing IBM i commands, which are context sensitive and should not be available as a command:
- `IBM i: New Connection` is only available when not connected (when connected it would disconnect the current connection without warning)
- the following commands are removed:
`IBM i: Login Settings`
`IBM i: Close` (search view)
`IBM i: Collapse All` (search view)
`IBM i: Debug Program`
`IBM i: Delete...` (in object browser)
`IBM i: Select for Compare`
`IBM i: Change...` (filter)
`IBM i: Sort Filters`
`IBM i: Move Up` (filter)
`IBM i: Move Down` (filter)
`IBM i: Sort Shortcuts`
`IBM i: Upload...` (streamfile)
`IBM i: Move Up` (library)
`IBM i: Move Down` (library)
`IBM i: Remove from Library List`
`IBM i: Refresh` (library list view)
`IBM i: Refresh` …
> Don't show context sensitive commands in Command Palette

- src/views/ifsBrowser.ts
When downloading a single IFS file, the extension in the File selection dialog is not right (it starts with `.`) and the dialog doesn't show the files with this extension:
This PR removes the `.` in the extension name and fixes this issue:
1. With version 2.8.0: try downloading a single file from the IFS browser: extension is wrong, no existing files with the extension are shown.
2. With the PR checked out: try downloading a single file from the IFS browser: extension is OK, files with the same extension in the folder are shown.
> Fixed file extension when downloading a single IFS file

- src/views/ifsBrowser.ts
- src/views/objectBrowser.ts
This fixes an issue preventing streamfiles from being dragged and dropped from the IFS browser.
Dragging a streamfile would trigger the following error, shown in the developer console:
That happened during the item JSON serialization finding a circular reference (i.e. `IFSFileItem`'s `command` would reference `this`, which indeed creates a circular reference).
To fix this, the command won't reference `this` anymore but only the required field to call the command (i.e. `this.path`).
The same fix has been applied on `ObjectBrowserMemberItem` to prevent the same problem in case it gets serialized.
1. Confirm drag'n'drop fails for a single streamfile without the PR (checkout the developer console to confirm the error)
2. Checkout the PR
3. Confirm drag'n'drop succeeds for a single streamfile …
> Fixed drag crashing for streamfiles

- src/api/Storage.ts
- src/instantiate.ts
- src/testing/index.ts
- src/testing/storage.ts
- src/webviews/settings/index.ts
* Removes old way of getting secrets from the connection
* Adds new command API, `getPassword`, which requests access from the user before allowing the extension to use the password. Alternatively, the user can deny an extension the password.
> Change secrets API

- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/api/Tools.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1935
Member names used to be uppercased regarless of the variant characters they may contain. Turns out that `à` is one of CCSID 297 (French) variant chars and it gets uppercased to `À`, which raises a `member not found` error.
This PR adds a new `upperCaseName` method to the `IBMi` class to correctly uppercase names, preservingthe variant chars case.
1. Set PASE_LANG environment variable to `FR_FR`
2. Open a connection with a profile whose CCSID is `297`
3. Try to open a member with one or more `à` in its name
> Correctly handle source members with variant characters in their name

- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/api/debug/index.ts
- src/filesystems/qsys/QSysFs.ts
- src/filesystems/qsys/extendedContent.ts
- src/instantiate.ts
- src/testing/connection.ts
- src/testing/content.ts
- src/views/LibraryListView.ts
- src/views/objectBrowser.ts
- src/webviews/filters/index.ts
- src/webviews/settings/index.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1935
The previous PR did not cover all the use cases for object names with a `à` on a connection with CCSID 297.
This PR replaces all the calls to `toUpperCase`/`toLocaleUpperCase` applied to object/member names with `IBMi.upperCaseName`. It fixes the issues where `à` gets wrongly upper cased.
1. Connect with CCSID 297
2. Create a library with a name containing `à`
3. In this library, create a source file with a name containing `à`
4. In this source file, create a member with a name containing `à`
5. Run actions from the library list view and object browsers on these items
> Replace all toUpperCase whith IBMi.upperCaseName where relevant

- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/api/debug/index.ts
- src/filesystems/qsys/QSysFs.ts
- src/filesystems/qsys/extendedContent.ts
- src/instantiate.ts
- src/testing/connection.ts
- src/testing/content.ts
- src/views/LibraryListView.ts
- src/views/objectBrowser.ts
- src/webviews/filters/index.ts
- src/webviews/settings/index.ts
This PR fixes the filters using the `Create Quick Filter...` action that would create a filter with wrong values for listing libraries.
1. Create a quick filter with value `Q*`
2. It must lists all the libraries starting with Q when expanded
> Fixed quick filter creation for listing libraries

- src/views/objectBrowser.ts
Fixes https://github.com/IBM/vscode-ibmi-projectexplorer/issues/422 (cc @edmundreinhardt)
The parameter types for the `code-for-ibmi.downloadMemberAsFile` command were recently changed to `BrowserItem` type, which prevented other extensions from using it without passing an object of this type.
By changing the expected type to `ObjectItem | MemberItem`, it allows other extensions to use this command again.
1. Download a member from the `Object Explorer`
2. Download a member from the [Project Explorer ](https://marketplace.visualstudio.com/items?itemName=IBM.vscode-ibmi-projectexplorer) Library List node.
> Use interfaces instead of classes for type checking

- src/api/local/deployTools.ts
- src/testing/deployTools.ts
- src/views/ifsBrowser.ts
Resolves https://github.com/codefori/vscode-ibmi/issues/1951
This adds the support for a `.deployignore` file that can be put at the root of a workspace to define patterns for files that should not be deployed by Code for IBM i when deploying a workspace. Files ignored during deployment can also be defined in `.gitignore`, but if `.deployignore` exists, it replaces `.gitignore` for this.
`.deployignore` supports the exact same format as `.gitignore`.
1. Run the test case `Test .deployignore` under `Deploy Tools API tests`
2. Create a `.deployignore` file in the workspace
3. Add a pattern to ignore something different from `.gitignore`
4. Deploy
5. Check the rules from `.deployignore` superseds `.gitignore`'s
> Added support for .deployignore

- src/api/IBMiContent.ts
- src/testing/content.ts
Fixes resolving members and objects having variant characters in their name.
Tests have been added to verify member and object resolve with variant characters.
Before this would not work:
After this fix the member resolution now works:
1. create a source member with variant characters in the name
2. open another source member and add /COPY or /INCLUDE referencing the source member with variant characters
3. Press `Alt-F12` with the cursor in the referenced member name.
4. Verify the referenced member content is shown.
5. Run the test cases
> Fix member and object resolve with variants

- src/api/IBMiContent.ts
- src/testing/content.ts
Fixes #1879. Prior to this PR, we were checking invalid libraries by looking for a text string that was specific to EN. That meant `validateLibraryList` did not work for non EN languages.
1. Run the test cases (we have a test case for `validateLibraryList`)
2. Add non existing libraries to the user library list and expect a warning that it does not exist
* Specifically trying this on multiple different locales
> Change library validation logic

- package.json
- src/api/debug/index.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/1987
Fixes https://github.com/codefori/vscode-ibmi/issues/1988
This PR fixes the two issues above:
- It allows for multiple IBM i debug sessions to be run simultaneously
- It restricts batch debug to *PGM only
Examples:
1. Check that `Debug as Batch` only shows on `.PGM` objects
2. Check that the `Start Debugging` menu shows even if a debug session is already ongoing
> Do not allow debug batch on *SRVPGM / Allow multiple debug sessions

- src/api/errors/diagnostics.ts
Fixes #1944, where if you had a member include from your local compile, it was not resolving in the Problems view correctly.
```rpgle
**free
// put this in YOURLIB/ASRCPF/AMBR.RPGLE
dcl-c MYNUMBER 27;
```
```rpgle
**free
/copy yourlib/asrcpf,ambr
dcl-s mytext char(1);
mytext = '1';
return;
```
After compiling the local workspace file, you should see the info message point to the member correctly.
> Fallback to system resolve if error file path not relative

- src/api/Tools.ts
- src/testing/tools.ts
Potential fix for #1984 where the columns were being parsed incorrectly and an incorrect amount of rows were being returned.
It'd be cool if we had a test for some Danish and French locale results to test the parser as well.
Examples:
> Improved support for DBCS output

- src/api/Tools.ts
- src/testing/tools.ts
Fix issue where empty columns were returning as zero.
Examples:
2. Make sure the object browser isn't showing '0'
> Fix issue where empty columns were returning as zero.

- src/api/debug/index.ts
Legacy logic to trigger the debug setup walkthrough, which as of 2.10.0 will no longer exist.
Examples:
1. Ensure you don't see the message when connected to a system with no debugger running.
> Remove debug walkthrough logic

- package.json
- src/views/ifsBrowser.ts
This PR will remove the dots from the "Remove Shortcut..." men item text, since there is no additional dialog.
It will also add protection for /QSR and /QTCPTMM directories.
1. Expand the IFS browser and right-click a shortcut. The menu item should read `Remove Shortcut` without any dots.
2. Expand `/` in the IFS browser and right-click `QSR` and `QTCPTMM`. Verify no menu option `Delete...` is available.
> Fix remove shortcut text and add additional protection

- src/api/debug/index.ts
Fixes #2011 and adds the `CPYENVVAR` to `SBMJOB` when batch debugging.
Examples:
1. Attempt the batch debug and expect it to work as normal.
> Update startBatchJobCommand to include CPYENVVAR(*YES)

- src/api/local/deployment.ts
Resolves https://github.com/codefori/vscode-ibmi/issues/1995
On systems <= 7.3, the deployed files are created with a CCSID 819 (or at least different from 1208).
This PR checks (once per connection, during the first deployment - the check result is cached) if the CCSID needs to be set to 1208 after a successful deployment and runs the `setccsid` command if needed.
Here is a query to list files with CCSID != 1208:
```sql
select path_name, ccsid
from table(qsys2.ifs_object_statistics( 
start_path_name => '/deployment/path',
subtree_directories => 'yes'))
where ccsid != 1208
```
This should be tested on two systems:
1. Deploy the local workspace
2. Check the progress says `Fixing files CCSID...`
3. If running an action, check the following log appear in the task log: `Deployed files' CCSID …
> Set CCSID of deployed files to 1208 if needed

- src/views/LibraryListView.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/2031
When changing the current library, `CHGCURLIB` is run to validate the new current library. If for some reason, the current `current library` cannot be accessed, `CHGCURLIB` will fail as the library list is wrong (i.e. it contains a library that cannot be accessed). This prevents the current library from being changed to fix the library list.
This PR changes the way `CHGCURLIB` is called so it doesn't use the library list.
Examples:
1. Create a temporary library
2. Set it as the current library
3. Delete the temporary library
4. Reconnect
5. Change the current library
Before the PR, step 5 would fail. With the PR, step 5 runs fine.
> Don't use library list to validate current library change

- package.json
Hide debug setup view when running Code for IBM i in managed mode
Examples:
1. Run Code for IBM i and expect to see the debug setup view
2. Run Code for IBM i in 'managed mode' and expect the debug setup view to be hidden
> Hide debug setup when being managed

- src/api/debug/index.ts
On the edge case when other extensions are setting the `DEBUG_MANAGED` variable, we now set the context when the connection is made.
Examples:
1. Set the environment variable `DEBUG_MANAGED` before connecting to a system and expect the debug setup view to be hidden.
> Change where manage debug context is set

- package.json
- src/views/ifsBrowser.ts
- src/views/objectBrowser.ts
Adds a shortcut to the Object Browser and IFS Browser to search the lists
Completes #2028 
1. Connect to a system
2. Click the Search icon on either the Object or IFS Browser
> Add shortcut to search object and IFS browsers

- package.json
Adds the `--resolveJsonModule` flag to the command generating the types to fix this error:
1. Apply the PR
2. Run `npm run typings` from a terminal
3. Types must be generated
> Fix types generation

- src/api/errors/diagnostics.ts
Fixes #2084
With this PR, whenever the `Clear Diagnostic on Edit` setting is enabled and a text document is changed, **all** (instead of just the first one) diagnostics are cleared when the diagnostics range contains the text document's change range.
1. Enable the `Clear Diagnostic on Edit` setting
2. Git clone [ibmi-company_system](https://github.com/IBM/ibmi-company_system)
3. Create an error on line 7 (refer to the linked issue)
4. Compile the file and observe 2 diagnostics in this range.
5. Fix the error and the 2 diagnostics should be cleared.
> Fix clearing of multiple diagnostics

- src/webviews/settings/index.ts
This PR fixes an issue where the settings' `privateKeyPath` would be set to `''` instead of `undefined` after an update, crashing the connection process afterwards with this message:
Before the PR, making any change not related to the password or private key in the settings would make the next password connection attempts to crash.
After the PR, connection attempts are OK after a change in the settings.
> Fixed privatekeypath update

- src/api/debug/index.ts
@sebjulliand In relation to the changes in https://github.com/codefori/vscode-ibmi/pull/2079, we noticed in Project Explorer (https://github.com/IBM/vscode-ibmi-projectexplorer/issues/486) that the current library was always being used to debug a program even though it belonged to another library.
1. Run debug from Project Explorer.
2. Run debug from Object Browser.
3. Run debug from active editor (local file, stream file, member).
> Fix object library being overwritten to current library for debug

- src/api/debug/server.ts
In its current state, the `Debug Service` item tooltip in the `IBM i Debugger` view shows too many ports:
The ports besides 8001 and 8005 are those used by the Service when it connects to the local TCP servers; they only appear once the Debug Service has been used at least once to debug a program:
This PR fixes the query used to fetch the Service ports to only get the server ports.
1. Connect to an IBM i where the Debug Service runs and has been used at least once
2. Go to the `IBM i Debugger` view
3. Hover over the `Debug Service` item
4. Only two ports must be shown at the top of the tooltip
> Only show server ports in Debug Service tooltip

- package.json
- src/api/Terminal.ts
- src/instantiate.ts
Adds a button to the terminal view that is displayed when the user attempts to type in an area where they cannot in 5250.
Not many users know the tn5250 shortcut (Control+R) to do a reset, so I added a button to the UI for it.
Examples:
1. Connect and launch a 5250
2. Sign in
3. Attempt to write outside an input field
4. See the button appear in the terminal tab
5. Click the button and see the cursor position reset
> Add 5250 keyboard reset button

- src/api/Storage.ts
- src/extension.ts
- src/webviews/settings/index.ts
- Fixed bullet 3 of https://github.com/codefori/vscode-ibmi/issues/2088 by updating the current listener on `code-for-ibmi.connections` to detect and delete stale cached server settings. Also, refresh the connection browser to remove any deleted connections
- Delete cached server settings when login settings are changed 
Examples:
1. Create a new connection and connect so there exists some cached server settings.
2. Manually delete the connection from the `settings.json` file.
3. Observe that the connection is removed from the connection browser view.
4. Create a new connection with the same name.
5. Debug the extension and observe that connecting to the new connection does not reuse the old cached server settings. 
6. Disconnect and use the `Login Settings` action to change to another …
> Delete stale cached server settings

- package.json
- Add refresh command for shortcuts and directories in IFS browser (command existed but was not contributed to the tree item)
- Remove unused `code-for-ibmi.refreshMemberBrowser` command
- Fix refresh command for the object browser tree items so only expandable items have the action
1. Verify the refresh action appears on expandable items in the IFS Browser and Object Browser.
> Add missing refresh action in IFS Browser

- src/api/IBMiContent.ts
- src/testing/connection.ts
The `countFiles` function ends up counting the number of files in the home directory when the directory that it is given does not exist. Although I have not noticed any issue in Code4i because of this, it causes an issue in Project Explorer (as it calls `getDeployCompareFiles`) where it shows that it is going to delete the contents of my home directory:
Without this fix, the issue can also be observed in the updated test where the `countFiles` result ends up counting the number of files in my home directory rather than the directory provided:
1. Use the test case provided
2. Use Project Explorer:
- Deploy your workspace
- Delete the deploy location using the IFS browser
- Refresh the source in the Project Explorer and observe the contents of the home directory is not visible unlike the …
> Fix `countFiles` when directory does not exist

- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/views/LibraryListView.ts
- src/views/ifsBrowser.ts
- src/views/objectBrowser.ts
- Add tooltips for libraries in the user library list view (just like the object browser)
- Add tooltip related APIs in `IBMiContent` to be used by Project Explorer:
- `objectToToolTip`
- `sourcePhysicalFileToToolTip`
- `memberToToolTip`
- `ifsFileToToolTip`
Check the following tooltips are rendering correctly
1. User Library List View - Libraries
2. Object Browser - Objects, Source Physical Files, Members
3. IFS Browser - IFS files/directories
> Add tooltips to libraries in the user library list view

- src/instantiate.ts
- src/views/ifsBrowser.ts
- src/views/searchView.ts
This PR will add a `readonly` value to IFS search and find results, to honor the default open mode set in the configurations.
When default open mode is `browse`, clicking on a search/find result will open the file in readonly mode.
Examples:
1. Set the default open mode to `browse` in the extension configuration
2. Create a search or find result
3. Click on one of the search/find results
4. Confirm the file is opened on readonly mode
5. Change the default open mode to `edit` in the extension configuration
6. Re-run steps 2 and 3
7. Confirm the file is opened in edit mode
> Use default open mode in IFS search and find results

- package.json
- src/api/debug/certificates.ts
- src/api/debug/config.ts
- src/api/debug/index.ts
- src/api/debug/server.ts
- src/locale/ids/en.json
- src/views/debugView.ts
- Do not perform Sanity Check (i.e. migration of certificate generated prior to v2.9) if current user doesn't have `*ALLOBJ` authority
- Added a `regenerate certificate` action in debug service's right click menu
- Moved `open configuration` action to debug service's right click menu
- Changed the logic of the method checking the debug service job status when it starts. It did not perform well on slow CPU and/or bad connection
- Debug service details cache is now cleared when disconnecting instead of connecting. That clearing could happen after the `IBM i Debugger` view title was loaded when connecting, leading to the wring version being displayed when switching between connections.
- IBM i debugger view loads slightly faster thanks to `Promise.all`
- Added an `Open output` action on the …
> Minor fixes and enhancements to debugger support

- src/api/IBMi.ts
- src/locale/ids/fr.json
- src/webviews/login/index.ts
This PR adds a `Save password and connect` button on the password prompt shown when connecting to a system whose password is not stored.
When clicked, the password will be stored only if the connection is successful.
1. Connect to a system whose password is not stored
2. Enter the password, press enter to connect
3. Disconnect
4. Connect again: the password prompt must show up again
5. Press `ESC`
6. Connect again: the password prompt must show up again
7. Enter the password and click on `Save password and connect`
8. Disconnect
9. Connect again: the password prompt must not show up
> Add Save password button on password prompt

- package.json
- src/api/Configuration.ts
- src/api/debug/index.ts
- src/views/debugView.ts
- src/webviews/settings/index.ts
This PR removes the `debugIsSecure` parameter from the connection settings.
Since the Service Entry Points requires a client certificate, there is no point in keeping the option to turn off secure debugging.
If the client certificate is not found locally or if there is a mismatch, the `IBM i Debugger` view will offer to download and update it locally.
A notification is shown in the status bar when the client certificate is being downloaded.
1. Connect
2. Go to the `IBM i Debugger` view
3. Check if the client certificate needs to be downloaded and click on the action to download it
4. Try debugging
> Always debug securely

- package.json
- src/api/Terminal.ts
This PR adds two global settings to enable opening PASE and 5250 terminals in the editor area.
Opening 5250 Terminal in editor area is enabled by default, since it requires more height than PASE.
The name of the connection for which the terminal is opened has also been added to the terminal title.
1. Connect
2. Open a 5250 terminal: it must open in the editor area
3. Open a PASE terminal: it must open in the panel area
4. Change the global settings to change the terminals location
5. Open PASE and 5250 again to see the change in effect
> Added settings to open PASE/5250 terminals in editor area

- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/api/Tools.ts
- src/api/errors/diagnostics.ts
- src/api/local/LocalLanguageActions.ts
- src/testing/action.ts
- src/typings.ts
Enables local actions to compile sources from source members. This enables the ability to use `CRTDSPF`, `CRTPF`, `CRTLF`, etc, on local workspace sources.
Examples:
1. Create a valid display file
2. Create an action in `actions.json` for `CRTDSPF`
3. Use the Action runner to use the newly action
4. Put an intential error in the display file
5. Run the action again and expect problems to appear
Also, run the test cases for Actions.
* New option in the Actions setup quickpick ✅
* Update the documentation on Actions
* Ability to define record length and CCSID of temp source file
> Compile non-IFS sources from local

- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/testing/content.ts
Fixes #2177 by not escaping at the right time.
* A new test case with members with dollar signs in the name has been added
* Renamed `sanitise` to `noEscape` to make more sense based on the existing code logic
Examples:
2. Try creating and editing a member with a dollar sign
> Fix and test case for supporting members with dollar signs

- src/api/IBMi.ts
- src/api/Search.ts
- src/api/Storage.ts
- src/testing/index.ts
- src/testing/search.ts
- src/views/objectBrowser.ts
- src/views/searchView.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/2207
Searching for text in members of a source file would crash if run on a "complex" filter. By complex, I mean a filter whose member filtering term is either a Regex or not a single generic name (`XXX*`).
This PR fixes this issue, making sure the search runs fine in all cases.
It also fixes some minor issues:
- The search progress message was still `Listing members...` even after the listing was done and `grep` was running
- The position used when opening a search hit could be wrong if the line started with one or more whitespaces
- The interval set for displaying different messages during the search was not cleared immediately when the search was over
1. Run a search on a simple filter
2. Run a search on a complex filter
In both …
> Fix `Search Source File` crashing when used with a complex filter

- src/api/IBMiContent.ts
- src/testing/content.ts
Listing objects and/or members with names containing variant characters using a profile with CCSID different from 37 would result in members being displayed with American variant characters and physical source files not being displayed or being displayed as regular PF.
Example, with CCSID 297 variants characters:
Before this PR, when listing members
After this PR
Before this PR, when listing source physical files:
With Object type = *ALL
With Object type = *SRCPF
After this PR
Turns out the system tables contains the names in CCSID 37 and the OBJECT_STATISTICS table function does translates the names to the connection's CCSID before returning the results.
1. Connect with a profile with CCSID other than 37
2. Create a member with one or more variant characters
3. It must be displayed …
> Fixed object/members listing failing when name contains variant chars

- src/api/IBMiContent.ts
- src/api/Terminal.ts
Some commands/methods were not working if the IFS path they received contained blanks, namely:
- Saving an IFS file whose CCSID was not Unicode (fixed `iconv` call)
- Opening a terminal
- Adding a new IFS shortcut
1. Create a folder with blanks in its name
2. Add its path to the IFS browser
3. Right-click and open a Terminal on it
4. Create a file in it with CCSID 850
5. Edit the file, make some changes, save it
6. Reload VSCode (the file may be in memory)
7. Open the file; changes must be kept
> Fixed IFS commands/methods crashing with paths with blanks

- src/api/debug/certificates.ts
- src/api/debug/config.ts
- src/api/debug/index.ts
- src/locale/ids/en.json
- src/views/debugView.ts
Since updating the Debug Service erases the service's configuration, two additional checks have been added when doing the Service's healthcheck:
- Check if the `CODE4IDEBUG` variable is found in the configuration file
- Check if the encryption key backup file exists (i.e. `/QIBM/UserData/IBMiDebugService/.code4i.debug`)
If the healthcheck fails on one of these items, the IBM i Debugger view will show this:
The `Generate certificate` inline action will be enabled on the Debug Service item so the situation can be addressed (i.e. regenerate everything).
1. Delete the `CODE4IDEBUG` in `/QIBM/ProdData/IBMiDebugService/bin/DebugService.env`
2. Refresh the IBM i Debugger view
3. It must show te error above and offer to regenerate the certificate
4. Generate the certificate
5. Delete the …
> Add additional checks for debug configuration/certificate

- src/api/IBMi.ts
We were not triggering the disconnect when the connection timed out. This was causing the database extension issues because the jobs tied to the connection were not going away because the extension was not signaled of the disconnect.
Real changes:
* Trigger `disconnect` and cleanup client when timeout happens
* Trigger `connected` no matter if connecting for the first time or if reconnecting.
Examples:
1. Use release version of the extension
2. Connect to server, spin up SQL job with database extension
3. Trigger the timeout somehow (disconnect from VPN in my case)
4. Use the reconnect option in the UI
5. See that the SQL jobs haven't ended, but are instead just handing
1. Use this branch of the extension
2. Connect to server, spin up SQL job with database extension
3. Trigger the timeout …
> Change logic for triggering disconnect

- src/api/CompileTools.ts
Changes
Changed the error message to make it more contextual when running an action while browsing a member (read-only mode). 
How to test this PR
Examples:
1. Open a member in browse mode.
2. Run an action using the keyboard shortcut.
3. New error message will be displayed in the VSCode message notification area.
Checklist
> #2105 Improved error when running an action in readonly mode

- src/views/ifsBrowser.ts
When dragging files or folders to a directory with special character(s) in the name of the source(s) or target, the copy or move fail the operation because of the special character(s) in the name(s).
This PR fixes the problem first reported in issue #2237.
Examples:
1. Switch to the master branch.
2. Drag and drop a file to a directory having a name with blank(s). The copy or move fails.
3. Drag and drop a file having a name with blank(s) to a directory. The copy or move fails.
4. Switch to this branch.
2. Drag and drop a file to a directory having a name with blank(s). The copy or move completes as expected.
3. Drag and drop a file having a name with blank(s) to a directory. The copy or move completes as expected.
> Fix error when dragging to IFS directory with special characters

- .github/workflows/pr.yaml
Fixes https://github.com/codefori/vscode-ibmi/actions/runs/10813160788/job/29996523037?pr=2038
Add the `build` label
> Upgrade deprecated `actions/upload-artifact@v2` to `v4`

- src/webviews/settings/index.ts
Fixes #2280 
The test controlling if the Download Client Certificate buttons in the connection settings was wrong: it would hide the button in case if problem (mismatch, not found, ...).
The test has been removed so the button always shows in the settings.
1. Remove local client certificate (located in user home directory)
2. Open connection settings
3. Go to the Debugger tab
4. The Download button should be visible
5. Click on the button
6. Re-open the settings
7. The client certificate should have been downloaded and the button should still be displayed
> Always show "Download client certificate" button

- src/api/IBMi.ts
- src/components/component.ts
- src/components/copyToImport.ts
- src/components/getMemberInfo.ts
- src/components/getNewLibl.ts
- src/components/manager.ts
- src/extension.ts
- src/instantiate.ts
- src/testing/components.ts
- src/typings.ts
- src/views/ProfilesView.ts
- src/webviews/settings/index.ts
Adds brand new export to the base API which allows other extensions to add their own installable components.
Components are checked on connection to ensure they are installed on the OS.
Examples:
2. Ensure extension starts up with existing components as usual.
> Extend the base API to allow other extensions to add their own components.

- src/api/IBMi.ts
- src/api/debug/certificates.ts
- src/api/debug/config.ts
- src/locale/ids/da.json
- src/locale/ids/de.json
- src/locale/ids/en.json
- src/locale/ids/fr.json
- src/locale/ids/no.json
- src/locale/ids/pl.json
- src/testing/debug.ts
- src/testing/index.ts
This PR takes the Java discovery part of https://github.com/codefori/vscode-ibmi/pull/2195.
The different possible Java installation locations are made into connection features.
These features are now used to get Java Home path when configuring the debug service.
1. Run the Debug test case
2. Generate a Debug Service certificate
3. Check Java Home in the Debug Service configuration file
> Made Java installation as connection features

- src/filesystems/qsys/QSysFs.ts
Fixes #2286
The path validity test was not valid for members located on an iasp.
This PR fixes the issue.
1. Open a member located on an iasp
> Fix stat() returning `Invalid member path` for members located on iasp

- src/filesystems/qsys/QSysFs.ts
Fixes #2289
Opening member located on an iasp from the member search result or from the `Go to` action failed because the URI would not contain the member's asp.
This PR fixes this issue by looking for the member on each known iasp if if fails to find it on `*SYSBAS`.
If the member is found on an iasp, the information is cached so any other member opened for the same library will automatically be done using the iasp previously found.
If a member is opened from the object browser, the library's iasp is also cached immediately to be reused if needed.
The library => iasp cache is cleared after disconnecting.
1. Search for members in a library located on an iasp
2. Open a member from the results
3. Use the `Go to` action to open a member located on an iasp
> Fix QSysFS iasp handling

- src/api/IBMiContent.ts
- src/filesystems/qsys/extendedContent.ts
- src/testing/content.ts
This PR will fix issue #2323 (originated from discussion #2316) by changing the SQL for QSYS.LIB objects to use the system name columns instead of the SQL name columns.
Examples:
1. Create a library as a DB2 schema with a long SQL name and shorter system name:
```sql
create schema  "Testing_a_long_schema_name" for TESTSYSNAM
```
2. Create a source file and member in this library:
```cl
CRTSRCPF FILE(TESTSYSNAM/SFILE) MBR(MBR)
```
3. Create a filter in the Object Browser for this library.
4. Expand the filter - with this change everything shows as expected, including tooltips.
> Use system names for libraries and source files in SQL

- src/api/IBMiContent.ts
This pull request includes a simple fix for always escaping the path when writing files. The `getAttributes` function has been updated to properly handle the path parameter for when bad characters, like a dollar sign, are used.
This fix also ensures that the encoding is correctly specified when using the `writeFileAsync` function.
Fixes #2303.
> Fix encoding issue when writing files

- src/sandbox.ts
SImple fix. TS compiler knew it was a string but our strict type generation wanted to be safe.
We don't need a release for this.
> Ensure type is a string for translation

- l10n/bundle.l10n.fr.json
- l10n/bundle.l10n.json
- package.json
- src/api/Configuration.ts
- src/filesystems/ifsFs.ts
- src/filesystems/qsys/FSUtils.ts
- src/filesystems/qsys/QSysFs.ts
Resolves #2300 
Based on @p-behr suggestion, this PR adds a new global settings that sets the action taken out by Code for i when a member/streamfile is left open when VS Code is closed and re-opened.
Supported values are:
* `ask`: opens a notification asking whether or not the user wants to reconnect
* `always`: always reconnect
* `never`: never reconnect
If the user choose to reconnect, the member/streamfile is reloaded. Otherwise, the editor that was left open is closed.
1. Open a member/streamfile
2. Leave it open and close VS Code
3. Re-open VS Code
4. Based on the reconnect setting, code for i will reconnect, close the editor or ask the user if they want to reconnect
> Add Auto Reconnect setting

- src/instantiate.ts
Fixes #2347 
Streamfiles were always opened using `vscode.openWith`, forcing VS Code to use the default text editor regardless of the file's type. Since `vscode.openWith` is used to be able to open the text editor at a given position, if we don't need to open at a position, we use `vscode.open` instead, allowing the editor linked to the file type to be opened, if any.
1. Install [vscode-pdf](https://marketplace.visualstudio.com/items?itemName=tomoki1207.pdf)
2. Connect to an IBM i
3. Open a PDF file from the IFS browser
4. The PDF editor must open to display the PDF file
> Use `vscode.openWith` only when necessary

- src/api/local/deployTools.ts
availabe -> available
Examples:
2. Expand view A and right click on the node
3. Run 'Execute Thing' from the command palette
> Fixed typo in deployTools

- src/views/ConnectionBrowser.ts
- src/views/ProfilesView.ts
- src/views/debugView.ts
- src/views/helpView.ts
- src/views/ifsBrowser.ts
- src/views/objectBrowser.ts
- src/webviews/actions/index.ts
- src/webviews/login/index.ts
Some messages were placed incorrectly, because of mistakes made after the `vscode.l10n` migration.
This PR fixes this.
It also fixes the `Open` action on the notification shown after downloading a physical source file. The action would run on Windows but not on *nix OSes, because of the file system's case sensitivity.
**Only on Linux/Mac os**
1. Download a physical source file
2. Click on the `Open` action in the `Download complete` notification
3. The download location must open
> Fixed incorrect messages + open members download location

- src/api/CompileTools.ts
- src/instantiate.ts
This PR simply adds the `workspaceFolder` as an optional parameter on `runAction`. The purpose of this change is so that when `runAction` is used on an object or member in Project Explorer, the local project's `LIBL` and `CURLIB` variables are used.
Associated change in PE: https://github.com/IBM/vscode-ibmi-projectexplorer/pull/575
1. Actions unrelated to PE should work as before.
2. Actions from PE should use the project's `LIBL` and `CURLIB`.
> Support workspace folder parameter on `runAction`

- src/api/local/deployment.ts
A new workspace watcher (used to track changes to be deployed) was created each time a connection was established.
This Pr makes sure only one watcher is created when the extension starts.
1. Open a local workspace
2. Make some changes in the local files
3. Deploy using the `Changed` method and check the correct number of files have been tracked
> Build workspace watcher only once

- src/api/IBMiContent.ts
Noticed in #2370 that the path was hardcoded. This PR removed the hard coded path and uses the default `attr` path found in the connection startup.
Test cases are still passing.
> Fix: Remove hard coded path to attr

- src/api/IBMi.ts
Introduce support for varying export syntax based on the shell type in the sendCommand method, accommodating both Bash and Bourne shell conventions.
https://unix.stackexchange.com/a/193137
Run this SQL statement to change your shell: `call qsys2.set_pase_shell_info('USERNAME', '/QOpenSys/usr/bin/bsh')`, then restart your connection.
Tests that use `getAttributes` are passing.
Will fix #2370.
> Add support for different shell export syntax in sendCommand method

- src/api/IBMiContent.ts
- src/testing/encoding.ts
Refactor date formatting to utilize the `safeIsoValue` function for better consistency and error handling. Add additional test cases to verify member text functionality. Will solve 'Invalid time value' error.
* The test cases for `getMemberList` are passing
* IFS Browser and Object Browser still functioning.
> Enhance date formatting and improve test coverage

- src/api/IBMiContent.ts
- src/testing/encoding.ts
Address issues with retrieving attributes for files that contain spaces in their names. Add additional test logic to ensure proper handling of such files and directories.
> Fix getAttributes for files with spaces and enhance tests

- package-lock.json
- package.json
- src/api/CustomUI.ts
- src/webviews/actions/index.ts
- webpack.config.js
Introduce the native file picker feature that allows users to select files through a button in the CustomUI. This change enhances user interaction by enabling file selection and updating the corresponding field with the selected file's path.
> Implement custom file picker functionality in CustomUI

- src/components/getMemberInfo.ts
`LONG_COMMENT` field in `qsys2.sysroutines` is VARGRAPHIC so the query used to fetch GETMBRINFO version crashes on systems with undefined Runtime CCSID since converting from CCSID 1200 to 65535 is not possible.
This PR casts `LONG_COMMENT` to `VARCHAR` to prevent the crash from happening.
1. Connect
2. Open the connection settings
3. Go to the Components tab
4. GetMemberInfo must show `(version 1): Installed` (before the PR, with Runtime CCSID 65535, it would show `(version 0): Error`
> Fixed GETMBRINFO status fetch crashing on system with undefind Runtime CCSID

- src/webviews/settings/index.ts
Fixes #2398
Examples:
1. Set `Default Deployment Method` to `No Default`
2. You should be prompted for deployment method without error.
> Fix `No default` deployment method not properly set

- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/api/Instance.ts
- src/api/Tools.ts
- src/api/debug/certificates.ts
- src/api/debug/config.ts
- src/api/debug/index.ts
- src/api/debug/server.ts
- src/commands/actions.ts
- src/commands/compare.ts
- src/commands/connection.ts
- src/commands/open.ts
- src/commands/password.ts
- src/components/cqsh/index.ts
- src/extension.ts
- src/instantiate.ts
- src/testing/action.ts
- src/views/debugView.ts
- src/views/helpView.ts
- src/views/ifsBrowser.ts
- src/views/objectBrowser.ts
- src/webviews/login/index.ts
Begin the process of deprecating legacy APIs/getters by updating references throughout the codebase to use new connection methods. This change enhances code maintainability and prepares for future improvements.
* Creates new generic `connect` and `disconnect` methods in `instance`, which is safer than calling `new IBMi()` to set the instance in the `connect` method.
* Split up `instantiate` so it doesn't hard code all commands inside of it.
* Move timeout handler and reconnect logic out of IBMi class.
* Remove all uses of `instance` in the IBMi class.
> Deprecate legacy APIs and update references

- src/api/debug/certificates.ts
- src/api/debug/config.ts
- src/api/debug/server.ts
- src/instantiate.ts
Resolves #2416
Applying Debug Service's PTF resets the `/QIBM/ProdData/IBMiDebugService` folder, including the `DebugService.env` holding Code for IBM i debug service config changes.
Since Debug Service 2.0.1, it is possible to use a custom `.env` file the start script will load when starting the debug service.
To take advantage of this, Code for IBM i will create a copy of the `/QIBM/ProdData/IBMiDebugService/bin/DebugService.env` into `/QIBM/UserData/IBMiDebugService/C4iDebugService.env` when connecting to a system, if `C4iDebugService.env` doesn't exist.
`/QIBM/ProdData/IBMiDebugService/bin/DebugService.env` won't me changed anymore and only `C4iDebugService.env` will be updated and used by Code for IBM i.
Starting the Debug Service >= 2.0.1 will set the …
> Manage custom `C4iDebugService.env` file to store Debug Service configuration

- package-lock.json
- package.json
- src/api/CustomUI.ts
- src/api/IBMi.ts
- src/typings.ts
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
Resolves #2442 and #2440.
This PR adds a new `readyTimeout` field to the connection settings (i.e. to the `ConnectionData` type). This field is described [here](https://github.com/mscdex/ssh2#client-methods).
A new `number` input has been added to the Connection/Login Settings to manage this field:
The `CustomUI` class has been enhanced to support the `number` input type as well as its `min` and `max` attributes.
The SSH port field has been turned into a `number` input.
1. Create a new connection with wrong credentials
2. Change the `Connection Timeout` field to 1000 (i.e. 1 second)
3. Try to connect: the connection attempt must fail after 1 second
4. Change the `Connection Timeout` field to 5000
5. Try to connect: the connection attempt must fail after 5 seconds
> New connection settings `Connection Timeout` field

- src/api/IBMi.ts
- src/components/getMemberInfo.ts
- src/components/getNewLibl.ts
`GetNewLibl` component state was not checked as it should. Instead of being checked in the corresponding component, it was added to the `IBMi::remoteApps` global array to be checked as a remote feature. This caused two issues:
- The actual version of `GetNewLibl` was not checked
- A new entry for checking `GetNewLibl` was added to the global array with each 'non-quick connect' connection attempts
This PR fixes this by:
- Not checking `GetNewLibl` as a remote feature anymore
- Handling `GetNewLibl` version in its component object
1. Connect
2. Check that `GetNewLibl` procedure get created in the connection temporary library with the version in its comment
> Correctly check GetNewLibl component state

- src/api/Tools.ts
- src/testing/tools.ts
> Fix bad character handling in extended byte calculation and add tests

- src/commands/compare.ts
Replace the hardcoded 'diff' command with a constant for improved maintainability and consistency in the code.
> Replace hardcoded 'diff' command with constant

- src/api/CompileTools.ts
- src/api/tests/suites/connection.test.ts
- src/ui/actions.ts
Patrick B raised an issue with me directly about this issue. 
>When I use the default commands I get the variable names in the prompt, but the command runs with the proper values.
>
> I have a couple of custom actions that aren't working properly...the variable names appear in the form, and are also used in the command:
This new change fixes the issue where the variables were appearing in both confirmation UIs before they were expanded.
Include unit tests for variable expansion in ILE commands.
> Enhance runCommand with error handling and event callbacks

- src/api/IBMiContent.ts
Ensure the function returns the default CCSID when the runSQL query yields no results.
I have found a system (`common1.iinthecloud.com`) which returns no rows when trying to get the CCSID of the SSHD job. If that is the case, then we just return the system QCCSID.
> Return default CCSID when no result is found in runSQL query

- src/api/IBMi.ts
- src/api/components/component.ts
- src/api/components/cqsh/index.ts
- src/api/components/getMemberInfo.ts
- src/api/components/getNewLibl.ts
- src/api/components/manager.ts
- src/api/configuration/storage/CodeForIStorage.ts
Improve code readability and maintainability by refactoring library and directory checks into separate methods. Introduce caching for component states to enhance connection performance.
Adds the component stats to the settings cache and validation each one individually. This will allow us to update one component without updating them all again.
Before:
After:
> Refactor component management and add state caching

- src/api/IBMi.ts
Deprecate the upload and download methods in the IBMi class, recommending the use of alternative methods for file operations.
This was needed as 2.14.5 has these APIs, and we can't remove them until 3.0.0.
Without this PR, the Db2 for i extension will break in the next release.
> Add removed APIs from `IBMi` class

- src/api/components/getMemberInfo.ts
- src/api/tests/suites/components.test.ts
This PR will fix the error reported in issue #2524 by returning the date `1970-01-01 00:00:00` when the source member date is not initialized, i.e. the date does not start with a '1' or '0'. This is the case when a member is created and not yet used: The QUSRMBRD API will return hexadecimal zeroes for the member change date if the member has never been refreshed.
A test for valid dates from GetMbrInfo has also been added.
Examples:
> Fix invalid dates from GetMbrInfo

- src/api/IBMiContent.ts
- src/api/components/getMemberInfo.ts
- src/api/components/manager.ts
- src/api/tests/suites/components.test.ts
- src/api/tests/suites/content.test.ts
- src/api/tests/suites/encoding.test.ts
- src/commands/open.ts
* move `enableSQL` to the connection instance.
* enhance component manager checks for `NotChecked` state
* Add missing away that was setting all cached states to `NotChecked`
* handle potential crashes when the `getMemberInfo` component is unavailable.
* fixed broken test introduced by another PR (where a date should have been returned correctly)
1. Ensure Go to File works as expected for opening members:
* `Try entering QSYSINC/*` to filter
* `Then try `QSYSINC/H/*` to filter
* Try opening `MATH`
> Refactor component handling and improve user input management

- src/api/IBMi.ts
`aspInfo` was removed and replaced by `iAspInfo`, but of course, `aspInfo` was public and is used in the database extension.
For 2.15.0 compatability, and the time period to allow extensions to change, I have added it back in but marked as deprecated.
Examples:
Test editing an SQL job in the database extension under the following versions of vscode-ibmi:
* production release 2.14.5: works
* pre-release/master: error due to `aspInfo` missing
* this branch/PR: works
> Deprecate aspInfo getter in preparation for IBMi.getAllIAsps in v3.0.0

- src/ui/views/objectBrowser.ts
1. Create an empty member in a sourcefile
2. Open VSCode, find the sourcefile and Select 'Download'
3. Empty members are downloaded.
> Mass source download fails on zero record members #2513

- src/api/IBMi.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/2531 by setting `LC_ALL` when using `cqsh` or `qsh`.
Run the test suite or query for objects in the Object Browser that contain NL chars such as in https://github.com/codefori/vscode-ibmi/issues/2531
> Set locale via `LC_ALL` when using `cqsh` or `qsh`

- src/api/IBMiContent.ts
The `CPDA08A` message ID should be parsed from `stderr` instead of `stdout`. I noticed this because the `Test streamfiles with shell character...` tests were failing.
Examples:
Ensure the `Test streamfiles with shell character...` tests pass
> Check for `CPDA08A` in `stderr` instead of `stdout` during member download

- src/filesystems/qsys/QSysFs.ts
Reuse retry logic to prevent endless loop when member fails to be read but stat indicates that it exists.
> Fix endless recursive retries to read member if it exists but fails to be read

- src/ui/Tools.ts
Add missing export from Tools class.
We do this as we don't export the internal Tools namepsace.
> Add makeid function export to VscodeTools namespace

- src/ui/views/ifsBrowser.ts
When the download of an IFS file fails, the error message is not correctly displayed:
This PR fixes the notification to correctly show the error message:
> Fix failed IFS download notification

- src/debug/server.ts
Resolves #2551 
This PR changes the checks performed when starting the Debug Service. It now allows a user with `*USE` authority on a profile with `*ALLOBJ` authority to start the debug service (i.e. when changing the USER parameter when prompted to submit the Debug Service start script).
If the user doesn't have the `*USE` authority on the other profile, an error will show up:
You'll need:
- a profile `A` with `*ALLOBJ` authority
- a profile `B` without `*ALLOBJ` and with no authority on profile `A`
1. Connect with profile `B`
2. Start the Debug Service and when prompted for the `SBMJOB` command, change the `USER` parameter to use profile `A`
3. An error must show up to inform you that you don't have `*USE` authority on profile `A`
4. Give `*USE` authority to profile `B` on profile `A` …
> Better authority check when starting Debug Service

- src/api/components/copyToImport.ts
Introduce new options for string delimiter and escape character in the CopyToImport component to ensure lines as escaped and can be parsed correctly.
Fixes #2553.
1. Open members that have double quotes in the lines (`"`)
2. Run the test cases
> Add STRDLM and STRESCCHR options to CopyToImport component

- src/ui/views/ifsBrowser.ts
- src/ui/views/objectBrowser.ts
For some reason, dropping members into the IFS browser now fails with this message.
Getting the members items from the `dataTransfer` object doesn't give the expected result (anymore?).
However, a URI list is automatically added to the `dataTransfer` when dragging items, so we now use that to perform the member copy to IFS operation.
1. Drag and drop a member from the Object Browser into an IFS folder in the IFS browser
2. The member must be copied to a streamfile in the target folder.
> Fixed droping QSYS members into IFS folder

- package.json
- src/commands/compare.ts
- src/instantiate.ts
This PR adds a `Compare with...each other` command that is enabled when exactly two members or streamfiles are selected in there respective browser:
The `Compare with...` submenu items have been renamed too, to avoid redundancy.
1. Select exactly two members or streamfiles
2. Select the `Each other` command in the `Compare with...` menu
3. Select just one member or streamfile: the menu must show 6 commands
4. Select more than two members/streamfiles: the menu must not be shown
> Added Compare with each other command

- src/webviews/CustomUI.ts
- src/webviews/variables/index.ts
Fixes #2590 
- Fixed variable edition (variable id was not retrieved correctly
- Added types for Custom Variables pages (list and editor)
- Removes any `&` in variable name
- Turn static class into namespace and refactored the code a bit
1. Open the custom variables list
2. Create a new variable: it must appear in the list
- Try to start the name with `&` : it must be removed
4. Edit the variable: save and the changes should appear in the list
5. Delete the variable: it must be removed from the list
> Fix custom variable editor

- package.json
- src/api/CompileTools.ts
- src/api/tests/suites/variables.test.ts
- src/api/types.ts
- src/api/variables.ts
- src/ui/actions.ts
- src/webviews/actions/index.ts
As discussed in https://github.com/orgs/codefori/discussions/2630
This PR adds a new setting to the Action definition - namely `outputFile`:
This field expects an IFS path and supports variables replacement as well as the special `&i` placeholder that, if present in the path, will act as an index that gets computed when the output is written (to avoid overwriting the previous output).
`~` is also supported and will be replaced by the user actual home directory.
For example, this pattern `~/outputs/&CURLIB_&OPENMBR&i.txt` will create these files if the action is run three time:
If the pattern is `~/outputs/&CURLIB_&OPENMBR&i.txt`, then a single file get written over and over again:
A new `Variables` object has been created to isolate the variables management (see src/api/variables.ts). …
> Add setting to write Actions output to an IFS file

- package-lock.json
- package.json
- src/Instance.ts
- src/api/Search.ts
- src/api/variables.ts
- src/commands/actions.ts
- src/commands/open.ts
- src/filesystems/local/actions.ts
- src/filesystems/local/deployment.ts
- src/testing/action.ts
- src/ui/actions.ts
- src/ui/views/ifsBrowser.ts
- src/ui/views/objectBrowser.ts
- src/ui/views/searchView.ts
- src/webviews/CustomUI.ts
- src/webviews/filters/index.ts
As discussed here: https://github.com/orgs/codefori/discussions/2612
This PR enables multi-selection support for the following commands:
- Generate binder source
- Browse/edit members
- Browse/edit IFS files
- Maintain filter
- Custom actions
- Search source file
- Search in IFS
- Find in IFS
Some noticeable changes were done to allow running custom actions on multiple items.
- All the selected items must share the same nature (i.e. URI scheme) (otherwise a warning is shown)
- If the command must be prompted ~~, it will do so for each item~~:
- If the action is run on a single item, it will be prompted as usual
- If the action is run on multiple items, it will be prompted once, keeping the variables placeholders
- The whole execution can now be cancelled. It will stop the process after …
> Enabled multi-selection support for several commands

- CONTRIBUTING.md
- src/api/tests/suites/variables.test.ts
- src/api/variables.ts
- src/testing/index.ts
1. Resolve issue with variable names by restoring a filter that was in previous code that was recently refactored (98a1b8880084dbea476fad43888a861921d52ecf)
2. Run the `before` function for individual test runs when the test suite has a `before`
This resolves specific problems documented in #2651 when trying to run the ***Variable expansion test***
Examples:
1. Build the code using `npm run webpack-dev`
2. Launch an **Extension Tests** instance from the **Run and Debug** section in VSCode
3. Open a workspace in the launched window, if not already open
4. Connect to an IBM i system
5. If running individually: Click on the ***Variable expansion test*** option from the **Test Cases** panel
6. If **not** running individually: The tests will execute after connection
Before changes, the …
> Fix #2651 variable expansion test is failing

- package.json
- src/api/configuration/config/ConnectionManager.ts
- src/ui/Terminal.ts
- src/webviews/settings/index.ts
Based on a tip shared by @alanseiden here: https://www.seidengroup.com/2025/05/21/improve-your-tn5250-experience-in-vs-code-for-ibm-i/
This PR changes the default connection string sent to Tn5250 when opening a new 5250 terminal. It adds `+uninhibited` to make it easier to get the cursor out of a protected area using any key.
The description of the connection string setting now also mentions `+uninhibited` so it can be copy/pasted in an existing connection string that would not  contain it already. 
1. Create a new connection
2. Check the default connection string under the Terminal tab of the connection settings is `+uninhibited localhost`
3. Open a 5250 terminal in VS Code
4. Enjoy a cursor that doesn't get stuck anymore
> Add `+uninhibited` to the default 5250 connection string

- src/instantiate.ts
Resolves #2062.
Revert the change made to fix this https://github.com/codefori/vscode-ibmi/issues/928#issuecomment-1295444916
Assuming this was due to QSYS FS `stat()` method not being fully implemented back then, it should be fine now it returns the actual member modification date.
1. Turn on Preview Mode in the settings
2. Open members
3. Check the output doesn't fill up with QSYS FS trying to load the member over and over
> Do not modify `workbench.editor.enablePreview` status on startup

- schemas/actions.json
- src/languages/actions/completion.ts
- src/ui/actions.ts
- Added the recently added `outputToFile` attribute to the local actions' schema and cleans it up.
- Added a snippet to easily define new actions.
- Added content assist to show variables on the `outputToFile` field since its supports variables replacement
- Moved the call to the `outputToFile` method before post download gets executed, so the output can be downloaded locally if needed
1. Open a local `.vscode/actions.json` file
2. Use content assist to check `outputToFile` is suggested as a field when defining an action
3. Use content assist when defining the `outputToFile` value to see the available variables
4. Define a value for an action's `outputToFile` and add the output file's parent folder path in `postDownload` then check the output file is downloaded.
> Complete actions schema

- src/api/IBMiContent.ts
- src/api/tests/suites/content.test.ts
- src/ui/views/ifsBrowser.ts
Fixes #2696 
As explained by @kadler in the IBM i OSS chat, QSH version of `cp` retain the CCSID of the original file into the copy.
Running the copy and move operations in QSH fixes the issue reported in #2696.
- Run the new  test case
- Check from the UI
1. Create a streamfile with CCSID != 1208 or 819: `touch -C 37 testfile`
2. Copy this streamfile using drag and drop in the IFS browser
3. Copy it also using the right-click `Copy` action
4. Check the CCSID of the copied file is 37: `attr copyOfTestFile CCSID`
> Run `cp` and `mv` in QSH to keep CCSID attribute

- webpack.config.js
Webpack build will now throw an error if the files that must be copied during the build are not found.
1. Add a file that doesn't exist or change the path of cqsh in the root `webpack.config.js` file:
2. Run `npm run webpack`: it must fail
3. Revert change made in 1.
4. Run `npm run webpack`: it must succeed
> Throw an error and abort build when file to copy is not found

- package.json
- src/api/types.ts
- src/extension.ts
- src/ui/views/LibraryListView.ts
- src/ui/views/ifsBrowser.ts
- src/ui/views/objectBrowser.ts
Related to https://github.com/orgs/codefori/discussions/2702
This PR enables users to reorganize their library list using drag and drop in the library list view.
- Dropping a library on the current library will make it the current library
- Dropping a library on a library in the list will push the library down in the list and put the dropped library in its place
- Dropping a library at the bottom of the view will put that library in last position
Dragging a library from an object browser's filter is also supported (it must be a single library filter or a *LIB object).
Multi-selection is also enabled.
1. Drag and drop a library on another libray in the library list view: it must take its place in the list
2. Drag and drop a library at the bottom the view: it must become the last library in …
> Enable drag and drop support in library list view

- src/api/configuration/storage/BaseStorage.ts
- src/api/configuration/storage/CodeForIStorage.ts
- src/api/configuration/storage/ConnectionStorage.ts
Implement a mechanism to set a unique key prefix for connection storage, ensuring that each connection maintains its own distinct storage context. This change enhances the organization and retrieval of connection-specific data.
> Ensure unique connection storage per session

- src/api/IBMiContent.ts
Use validQsysName rather than individual checks. #2366 
Removed individual checks within `validateLibraryList` method and changed it to `IBMI.validQsysName` method.
I tested this change by using the `Add to Library List` command. I tested adding a library name of '!@#$%'.
I wasn't able to test the length > 10 case, because there is a check in `code-for-ibmi.addToLibraryList` for that case, before the call to `validateLibraryList`.
I noticed that there was some test suites that tested `validateLibraryList`, but I wasn't sure how to run them. Is there a way for me to call these test suites? Thanks.
> Update IBMiContent.ts to use validQsysName

- src/api/IBMi.ts
- src/api/tests/suites/content.test.ts
- src/api/types.ts
Looks like there is a bug with our node library. We have an instance when an IBM i system is not setup correctly, then SIGABRT is thrown, but the `code` is still `0` - which in most of the extension, indicates success.
```
/home/OLVERA: /home/OLVERA/.vscode/cqsh_1
echo "Hello world"
{
"code": 0,
"signal": "SIGABRT",
"stdout": "",
"stderr": ""
}
```
I've added some logic to our statement executor to set the code to `127` when `SIGABRT` is thrown.
I have also added a page in the docs to track this issue (which we've now seen a couple of times in the wild, but we are still unsure of the cause): https://codefori.github.io/docs/tips/setup/#qsh--cqsh-returning-sigabrt
> Add additional check for SIGABRT

- src/api/tests/suites/content.test.ts
- src/ui/views/ifsBrowser.ts
Fixes #2725
The `reduceIFSPath` that is supposed to filter out IFS elements from an array whose parent folder is in that same array.
There was a bug that made the function filter out elements that started with a folder name present in the array.
For example, when selecting these three folders, only one would be picked up for deletion:
After the PR is applied, the three folders are correctly picked up:
And the method still filters out elements with a common parent item (e.g. selecting a folder and its files):
1. Create two or more folders starting with the same name
2. Select them all and run the `Delete` action
3. All folders should be picked up for deletion
> Fixed multiple download/delete of IFS directories starting with the same name

- package.json
- schemas/codefori.json
- src/api/IBMi.ts
- src/api/configuration/config/types.ts
- src/api/configuration/serverFile.ts
- src/webviews/CustomUI.ts
- src/webviews/settings/index.ts
It's been quite clear we need a way to set a default configuration for all users that connect to a specific system. This adds a new config file that will be read on startup, `/etc/vscode/codefori.json`, and will do two things:
* apply the server settings to the user's connection config
* disable those properties from being edited in the UI
You will also notice that not all properties were added to the settings schema. I didn't add anything that could come down to personal preference, like _source date gutter_.
1. Connect to a system with no system config file
2. Ensure all connection setting fields are editable
3. Create `/etc/vscode/codefori.json` and test that the JSON schema is working as expected
4. Restart the connection and ensure the fields that were configured in the server …
> Server configuration and apply to every client

- package.json
- schemas/settings.json
This PR will add the Readonly Mode setting to the server settings file, allowing the system admin to set the connection to read only:
> Add read only mode to server settings file

- src/debug/server.ts
Changed **Debugger Service** submission command
Now, all parameters in the SBMJOB command are using default parameters: SYSLIBL(*SYSVAL) CURLIB(*USRPRF) INLLIBL(*JOBD)
Closes #2785
> Changed debug service submission to have default library configuration

- src/api/IBMi.ts
- src/api/IBMiContent.ts
- src/api/Tools.ts
- src/api/types.ts
- src/typings.ts
Relocate the `EditorPath` type definition from the `typings` directory to the `api` directory for better organization and accessibility.
This is to correctly singularise the `api` directory so it doesn't depend on the `vscode` namespace.
> Move EditorPath type to api directory

- src/api/IBMi.ts
- src/api/tests/connection.ts
- src/api/types.ts
- src/commands/connection.ts
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
The cause of a connection failure was never reported after it happened. This PR fixes this and add the error message in the error notification.
It also adds error details (error JSON representation + stack trace) into the output to help diagnose connection issues.
This should help with #2856 and #2840 .
A new `SSH debug output` option has been added in the Login settings:
When turned on, it will append SSH debug traces to the Code for i output.
1. Connect to a system with the wrong address or credentials. Or shut down the SSH server on the LPAR
2. Check out the error notification to see the cause of the issue
3. Check out the Code for IBM i output for error details
> Display connection error message + add detail in output

- src/ui/views/ifsBrowser.ts
- src/ui/views/objectBrowser.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/2897
Warning when copying members with unsaved changes:
Warning when copying stream file with unsaved changes:
1. Create member or stream and make some change without saving.
2. Attempt to copy it and check the warning appears.
> Add warnings when copying members/streamfiles with unsaved changes
