codefori/vscode-ibmi

- package-lock.json
- package.json
- src/api/IBMi.js
- src/webviews/login/index.js
- src/webviews/login/login.html
Thanks to @richardschoen for his work here.
> Add port to connection details (richardschoen-master)

- package.json
- src/Instance.js
- src/api/CompileTools.js
- src/api/IBMi.js
This adds
* New output channel for spool files
* New config option to enable spool printing
> Log spool files into output channel

- README.md
- package-lock.json
- package.json
- snippets/cl.code-snippets
Added some defaults for CL compilations and a few CL snippets
> Add CL compile and CL snippets

- snippets/cl.code-snippets
> Add more CL Command snippets

- README.md
Add new section at the bottom.  Also added info on SSH program product.
> Add Link to Detailed Documentation

- README.md
- package.json
- src/api/IBMiContent.js
- src/views/objectBrowser.js
* Added ability to create a source PF from the right click menu of object browser
* Corrected an issue when only 1 file exists in a library in object browser
* Added clarification to UI that underlying IBMi object will not be removed when taking remove options
* [N/A] updated relevant documentation
* [N/A] Remove any/all `console.log`s I added
> Object browser changes

- package-lock.json
- package.json
- src/api/CustomUI.js
Added ability to add a checkbox to CustomUI webview panels
> Add Checkbox to CustomUI

- src/api/IBMiContent.js
If `db2util` is enabled, we will use SQL to fetch the member list.
> getMemberList to use SQL when available (#91)

- src/api/CustomUI.js
- src/webviews/login/index.js
I've expanded on the work done by @onewheelonly and added a file picker for the SSH Key.
> Add File Picker for SSH Key

- src/webviews/login/index.js
Resolution to #88 
Quick change to immediately display the password prompt (or eventually login without prompt) if there is only one
> Requested Change #88

- README.md
- package.json
This change adds the new default action CRTPNLGRP command for members of type PNLGRP.
> Add CRTPNLGRP command for members of type PNLGRP

- README.md
- docs/README.md
docs/README  
- OUTPUT font size
- db2util & enableSQL
-  Tips & Tricks added:  OverType 
- misc typos/formatting
README:
- misc typos/formatting
> README changes

- package.json
- src/Instance.js
- src/api/CompileTools.js
Adds a way to clear the diagnostics.
> Clear diagnostics command (#25)

- src/api/IBMiContent.js
This replaces an SQL statement that doesn't work when users don't have almost highest authority.
> Change SQL to get members to not use SYSSCHEMAS (#155)

- src/api/IBMi.js
Adds progress notification to the connection process.
> Add progress bar into connection process (#205)

- src/Instance.js
Adds a prompt before showing available Actions to save the file. 
#201
> Add prompt to save file if dirty when running Actions (#201)

- src/languages/rpgle/linter.js
Extends the experimental features for RPGLE to include an outline view for completely free-format RPGLE.
*  X] Remove any/all `console.log`s I added
> Outline view for RPGLE

- src/api/IBMi.js
> Provide text description for tempLibrary

- docs/README.md
Updated documentation of temporary library to be more detailed and useful.
> Explain purpose of temporary library

- docs/README.md
Question by me today to a customer who saw that MIMIX flagged this object as new: "Would it be possible to add it to an exclude or ignore list in MIMIX just in case it gets created again?"
Reply by customer to his MIMIX expert "Good idea!  Please have Mimix ignore library ILEDITOR."
> Add yet more info about temporary library

- README.md
Added compare and upload/download to the readme.  Seems like those are fairly important features.
> Compare, Upload & Download added to readme

- README.md
- package.json
- src/Instance.js
- src/api/Configuration.js
- src/api/IBMi.js
- src/filesystems/qsys/basic.js
- src/filesystems/qsys/complex.js
- src/filesystems/qsys/complex/content.js
- src/filesystems/qsys/complex/handler.js
- src/filesystems/qsys/complex/sourceDates.js
- src/webviews/settings/index.js
* Implements a new file system provider to support downloading and uploading members with their source dates.
* Shows current lines source date 
* Two new configurations for 1. enabled source date support and 2. showing the source date on the line
> Implementation of source date support

- package.json
- src/views/memberBrowser.js
Instead of showing a plain list of shortcuts, we now group all shortcuts into their library, and under that their source files.
Resolves #278
> Improvements to member browser

- package.json
- src/extension.js
- src/views/connectionBrowser.js
- src/webviews/login/index.js
* Adds new server browser to see all your connections at once
* Right-click option to delete connections
* Ability to add a new connection with a plus button
* Other views are hidden until a connection has been made
* server browser hidden after the connection has been made
* groundwork for a connection editor 
Resolves #280
> Initial server browser

- package.json
- src/webviews/settings/index.js
Brand new right-click menu to manage login settings for a connection.
From #303
> Way to manage login settings

- package.json
- src/views/ifsBrowser.js
Adds copy file function to IFS streamfiles. Take the option to copy and it will ask for a path to copy to as per "move" command interface.
> Add Copy File option to IFS Files #311

- docs/api/custom-ui.md
- src/api/CustomUI.js
- src/webviews/actions/index.js
* Adds `buttons`, to support many buttons appearing in a custom UI.
* Adds `tabs`
* Updated the Actions UI to show off how these new buttons work
> New Field type for CustomUI

- src/api/Search.js
- src/views/ifsBrowser.js
- src/views/memberBrowser.js
Adds a progress bar to indicate the search is still happening for both member and IFS searches.
> Member and IFS progress

- src/webviews/actions/index.js
Adds a delete button when maintaining an existing action.
> New button to delete an action

- package.json
- src/api/CompileTools.js
* Grab errors from whatever library the object was compiled in.
* Add missing `*EVENTF` from some default actions.
> Improved error handler

- src/languages/rpgle/columnData.js
- src/languages/rpgle/linter.js
* Fix issue where spaces were cleared out
* Fix issue where new line was not fully replacing old line
> Improvements to RPGLE column assist

- src/languages/rpgle/linter.js
Now the user can highlight the diagnostic and allow the CodeAction to fix the indentation.
Closes #387.
> Add CodeActions for indentation issues

- src/api/IBMiContent.js
- src/views/ifsBrowser.js
Previously you could not browse or open files with spaces in them. This PR fixes that.
> Support for spaces in streamfiles and directories

- .vscode/extensions.json
- src/api/CompileTools.js
- src/api/CustomUI.js
- src/webviews/actions/index.js
* Let's the user specify one command per line
* Button to show output log when spool logging is enabled 
* Improvements to multiline support
> Ability to run many commands in an Action

- docs/README.md
- package.json
- src/api/CompileTools.js
- src/schemas/actions.json
* For projects that are open in the local workspace, you can now define actions for the local file system.
> Support for actions to be defined in workspace

- package.json
- src/Instance.js
- src/api/IBMi.js
- src/webviews/login/index.js
* New VS Code configuration to show the 'force reconnect' button in the actions bar
* Timeout warning message now shows up in the center of the editor to capture the attention of the user in case of a timeout.
Implements #461
> New force reconnect button

- src/api/Configuration.js
- src/api/IBMi.js
- src/api/IBMiContent.js
- src/webviews/settings/index.js
With this PR, we can directly call the `db2` symlink if it does not exist. Another useful fallback for the executor list.
> New executor

- package.json
- src/api/Configuration.js
- src/api/IBMi.js
- src/webviews/settings/index.js
Adds new connection settings to automatically clear old temp files when connecting.
> New config to clear temp data on startup

- src/Instance.js
- src/views/libraryListView.js
* Validate library list when item is added
Implements #517
> Validate library list when it is updated

- docs/README.md
Goofed on last change--sorry.  Used wrong link and left one out.  Brain dead at times...
> Readme: fix RPGLE tools & Development Pack

- docs/README.md
- package.json
- src/api/Configuration.js
- src/api/IBMi.js
- src/webviews/settings/index.js
Make IFS temporary directory configurable
> Make IFS temporary directory configurable solves #498

- package.json
- src/Instance.js
- src/api/Search.js
- src/views/ifsBrowser.js
- src/views/objectBrowser.js
- src/views/searchView.js
New UI to show search results. Closes #546
> Add new UI that displays search results

- CONTRIBUTING.md
- README.md
Add new CONTRIBUTING file.
Closes #545
> Worksofliam contributors

- docs/README.md
- package.json
- src/api/CompileTools.js
- src/api/Deployment.js
- src/api/IBMiContent.js
- src/webviews/actions/varinfo.js
Allows the user to deploy a local workspace to a chosen library.
> Deploy: Deploy to chosen library

- src/api/CompileTools.js
- src/api/IBMi.js
- src/api/IBMiContent.js
- src/api/Search.js
- src/views/libraryListView.js
* Deprecate `paseCommand` and `qshCommand`
* Add `sendCommand` and `sendQsh`
> API cleanup

- docs/README.md
- package-lock.json
- package.json
- src/api/IBMiContent.js
- src/views/databaseBrowser.js
* Update `csv-parse` to `csv`
* Redesign SQL result set table
* Add `json` and `csv` as SQL options, similar to `cl`
> SQL results improvement

- package.json
- src/api/Configuration.js
- src/filesystems/qsys/complex/handler.js
- src/webviews/settings/index.js
* Removes old methods of viewing source date
* New config to show source dates in gutter
> New option to have source dates appear in gutter

- CONTRIBUTING.md
- src/api/CompileTools.js
Replaced string scanning code in function **_getObjectFromCommand(...)_** with a regular expression allow more reliable parsing of the target object parameter for command actions.
Resolve #576
> Resolve issue #576

- src/views/ifsBrowser.js
Support uploading many files to the IFS.
> Ability to upload many files

- src/api/CustomUI.js
- src/api/Search.js
- src/views/ifsBrowser.js
- src/views/objectBrowser.js
Member search now respects filter.
Closes #601.
> Member search now respects filter

- docs/README.md
- say "checked" rather than "enabled" to give confidence
- add gutter setting
> Updates for source dates

- src/views/ifsBrowser.js
> fix typo (remove "and")

- src/views/ifsBrowser.js
Small fix of wrong wording of error message for copying streamfile.
> Fix wording in error message for copying streamfile

- src/Instance.js
- src/api/Tools.js
- src/views/objectBrowser.js
Added object name validation to the Tools member path parser.
Use the Tools parser in Instance.openFileByPath and objectBrowser.renameMember
When copying a member, moved the showInformationMessage until after we validate the paths.
In Tools.parserMemberPath we validate the system object names.
Instance and objectBrowser had a couple spots where they were doing their own parsing; changed to use Tools parser.
* Open/Save member
* Compare source
* Update text
* Copy member
* Rename member
* Delete member
* Open file by path (member & IFS) 
* Download/Upload member
> Added object name validation to Tools.parserMemberPath.  

- src/views/objectBrowser.js
> Check for change in source type extension when copying a member

- package.json
- src/views/ifsBrowser.js
This PR will add the Copy option to IFS directories to allow copying directories in the IFS browser.
> Add Copy option for IFS directories

- src/api/Tools.js
> Add § to the valid system names regexp.

- global.d.ts
- package-lock.json
- package.json
- src/Instance.js
- src/api/CompileTools.js
- src/api/Deployment.js
- src/schemas/actions.json
- src/views/ifsBrowser.js
- src/webviews/actions/index.js
* Better EVENTF support for local files that use the ibmi-bob naming format.
* Remove `deployFirst` option for interactive Action editor.
* Ability to download files as part of local action execution
* New messages show when a connection is made with a single workspace open.
> Local workspace improvements

- src/api/IBMiContent.js
This PR will fix issue #743 by changing SQL for member list to convert nulls in member type and text to empty string.
> Fix empty member list when a member has no source type

- docs/README.md
This PR adds a thorough description of the CCSID problem between IBM i and Code for IBM i, and how to set a specific CCSID/language for a user.
Please review this carefully - English is not my first language! 😄
> Describe new CCSID handling

- src/webviews/actions/index.js
This PR fixes issue #772 by removing the Delete button from the view for new action.
> Remove Delete button from new actions view

- docs/pages/api/extending.md
- global.d.ts
- src/api/IBMi.js
- src/extension.js
Adds new API to connect to a system programatically.
> New API for connecting to a system

- src/api/CompileTools.js
Cleanup of how variables get replaced in command string.
> Improved variable handling

- package.json
Add a button "Clear diagnostics" on the editor view
> add button "Clear diagnostics" on the editor view

- CONTRIBUTING.md
- docs/pages/tips/setup.md
Recipe for when Connection fails on ssh private key format
* [ x] have tested my change
* [ x] updated relevant documentation
* [ x] Remove any/all `console.log`s I added
* [ x] eslint is not complaining
* [ x] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
> Ssh weirdness

- package.json
- src/Instance.js
Add a disconnect button to status bar.
> Add a disconnect button to status bar

- src/views/libraryListView.js
- src/views/objectBrowser.js
When creating a library, ask for adding the new library in the library list. Then ask for saving the profile.
* [] **for feature PRs**: PR only includes one feature enhancement.
> Add the new library in the library list

- package.json
- src/Instance.js
Go to file by entering directly the path (Library / File / Member)
> Go to file by entering directly the path (Library / File / Member)

- package.json
- src/views/objectBrowser.js
This PR will
- add commands to move a filter up and down in the object browser
- add commands to move a filter to top or bottom of the list in the object browser
- add command to sort the filters by name in the object browser
It will solve the request made in issue #861
> Allow filters to change position

- package.json
- src/views/objectBrowser.js
This PR will add a command for changing object description:
> Add command for changing object description

- package.json
- src/views/objectBrowser.js
Added Copy, Delete, Rename, and Move to Object Browser object context options - Issue #826
> Added copy, delete, rename, move object browser context menu options

- src/Instance.ts
- src/views/helpView.ts
* Converted helpView to TypeScript (let's start small)
* Made `instance` a const
> Converted helpView to TypeScript

- src/api/IBMi.ts
- src/api/Instance.ts
Added a few methods in exported API:
* Getters for connection `name`, `host`, `user `and `port`
* `uploadFiles`
* `downloadFile`
* `onEvent` to easily subscribe to connection events
> Added methods/facilitators to exported API

- src/api/Instance.ts
- src/instantiate.ts
A 'disconnected' event is now fired when disconnecting.
> Fire a 'disconnected' event when disconnecting

- src/extension.ts
- src/sandbox.ts
Addition of sandbox mode features for a feature coming soon.
> Sandbox mode

- src/extension.ts
- src/sandbox.ts
Adds the ability to connect via URI handler
> Connect via URI handler

- package.json
Changed extension's activation event to [onStartupFinished](https://code.visualstudio.com/api/references/activation-events#onStartupFinished), so it can handle whatever it needs to right away.
> Activate extension on startup finished

- src/sandbox.ts
- src/typings.ts
* Additional `save` query parameter on URI handler. This stores the connection so it can be re-used locally
* If username is not provider, ask for user profile
* Ability to pass port in via `server` parameter
* Local URL now generates unique name
> Additional sandbox features

- CONTRIBUTING.md
- src/api/IBMi.ts
Just fixing a typo in a log message.  It was bothering me as I was working with it, so I decided to just create a PR for it.  If you don't want me to be added to the CONTRIBUTING.md for a change this inconsequential, I understand.  Feel free to remove that line before merging.
> Fix typo in "Connection lost" error message

- package.json
[Commands in command palette only shown when there is a connection.](https://github.com/halcyon-tech/vscode-ibmi/issues/968)
* [] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
> Command: only shown when there is a connection

- package.json
> Correct Action description

- CONTRIBUTING.md
- package.json
- src/views/objectBrowser.js
- src/webviews/filters/index.js
Add the ability to copy a object filter
* [] have added myself to the contributors' list in [CONTRIBUTING.md](https://github.com/halcyon-tech/vscode-ibmi/blob/master/CONTRIBUTING.md)
> [Object filter] Add copy filter

- src/api/local/deployment.ts
- src/typings.ts
Deployment related types were not correctly exported.
> Fixed Deployment types export

- src/api/IBMiContent.ts
- src/views/ifsBrowser.js
Handle permission denied in IFS browser.
Show an error message if permission is denied.
> Handle permission denied in IFS browser

- package-lock.json
- src/api/CompileTools.ts
- src/api/Tools.ts
- src/api/local/deployment.ts
- src/sandbox.ts
> Handle git as optional feature

- README.md
> Add contributors graphic to README

- src/api/debug/index.ts
- src/api/debug/server.ts
* Uses fixed Java version when starting the debugger
* Added more error messages when ending and starting the debug service
Fixes #1079
> Fixed Java version and better error handling

- package.json
- src/api/Search.ts
- src/views/ifsBrowser.js
- src/views/objectBrowser.js
- src/views/searchView.ts
This PR will enhance searching by
- Sort the search results (IFS search result could previously be mixed)
- Show subdirectories in IFS search result (previously only the basename was shown)
- Show member and type in upper- or lowercase in search results, like names are shown in the Object Browser
- Add a tooltip to the search results, showing the full path of the member/file
- Add a button to collapse all elements in the search result
> Search enhancements

- CONTRIBUTING.md
- package.json
- src/views/ifsBrowser.js
- src/views/objectBrowser.js
add buttons to collapse the file in object Brower and ifs browser view.
About  updated relevant documentation I Have'nt seen usefull modification to do...
> Collapse all on IFS Browser and Object Browser #876

- package-lock.json
- package.json
* Looks like we had some unused deps. I removed them, did a fresh install and package and it's still building as expected.
> Cleanup package dependencies

- CONTRIBUTING.md
- package-lock.json
- src/api/IBMi.ts
Adds feature described in #1074.  Give user option to set bash as their default shell.
> Give user option to set bash as their default shell when connecting.

- src/views/objectBrowser.js
Add member text to tooltip - idea from issue #1140
> Add member text to source member tooltip

- src/api/CompileTools.ts
- src/api/local/deployment.ts
- src/instantiate.ts
* Correctly hides Deploy button when the user disconnects
* Fixed bug where Output button was not spinning while Action was running
* Turns out we were registering two Output buttons!
* Fix bad text when cancelling Action selection
> Fix/status bar Deploy and Output buttons

- src/views/ConnectionBrowser.ts
- src/webviews/settings/index.ts
Converts settings UI JavaScript to TypeScript.
> Convert Settings UI to TS

- src/testing/connection.ts
Tests for:
* Sending ILE command
* Sending ILE command with custom library list
* Sending QSH command
> sendCommand tests (QSH/ILE)

- src/api/CompileTools.ts
> Remove rogue liblist command

- src/api/local/deployment.ts
- src/typings.ts
Add new `deploy` event to `IBMiEvent`.
> Add new `deploy` event

- src/testing/ileErrors.ts
- src/testing/index.ts
As base for tests for the error handler. Only contains one test thus far.
> First tests for the error handler

- src/api/IBMiContent.ts
- src/testing/content.ts
> Completed object resolve api + tests

- src/views/helpView.ts
- Added warning to remove sensitive content
- Added notification to copy full data in clipboard if too long
- Added a few emojis
> Minor issue reports enhancements

- src/api/local/deployment.ts
- Fixed deployment API not deploying when called externally with not ignore rules
- Added default ignore rules (to not deploy git related files) when none provided
> Fixed deployment API

- src/api/IBMi.ts
Handles #1337.
* Adds error messages (`stderr`) to shell error modal
* Show 'Read more' button to open docs page with more info regarding this error
> Shell checker: Show error and read more button

- package.json
Bump version to 1.9.3 for upcoming release
> Bump to 1.9.3

- package.json
Bumped version to 1.9.4 for a new release
> Bump version to 1.9.4

- CONTRIBUTING.md
- src/api/CompileTools.ts
- src/api/IBMi.ts
- src/api/Tools.ts
- src/api/errors/handler.ts
- src/api/errors/handlers/new.ts
- src/api/errors/handlers/old.ts
- src/api/local/deployment.ts
- src/testing/connection.ts
- src/testing/content.ts
- src/testing/deployment.ts
- src/testing/ileErrors.ts
- src/testing/index.ts
- src/testing/testCasesTree.ts
- src/webviews/settings/index.ts
Always show Terminals and Debugger tabs in connection settings, warning the user if they need to connect or enable a service to change the settings.
> Always show Terminal and Debugger tabs in settings

- package.json
This PR will fix the display of menu items from this
to this:
> Fix IFS shortcuts menu items order

- src/api/CustomUI.ts
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
* Adds `minlength` and `maxlength` to input fields.
* Add real time validation to input fields to indicate that some fields are required
* Button fields can indicate that for them to be clicked all fields need to be valid
* Enter on a field doesn't work unless all fields are valid
> Ability to add validation to input fields

- src/views/ifsBrowser.js
This PR will fix the error occurring when no files were selected for upload:
> Fix error when no files are select for upload

- src/webviews/login/index.ts
- src/webviews/settings/index.ts
Add note about supported private key formats: OpenSSH, RFC4716, or PPK formats are supported.
> Simple note about private key formats

- src/api/IBMi.ts
- src/instantiate.ts
- src/testing/connection.ts
- src/testing/content.ts
- src/views/ifsBrowser.js
- src/webviews/login/index.ts
- src/webviews/settings/index.ts
* Removes deprecated APIs and tests for them for the 2.0.0 release.
> Remove old deprecated commands

- src/api/Search.ts
This PR will
- fix searching IFS objects for backslash and doublequotes
- fix seaching members for doublequotes
> Fix minor search errors

- src/api/IBMi.ts
> Remove check for excessive authority

- package.json
- types/package.json
Change version numbers for release.
> Bump to version 2.4.0

- package-lock.json
- package.json
- src/api/CompileTools.ts
- src/api/local/env.ts
* Sets branch new `&BRANCHLIB` variable for running an Action out of a branch. ([Docs need additional logic](https://github.com/codefori/docs/pull/19) for this when merged)
* Adds logic in to recursively resolve variables in variables. For example: `CURLIB=&BRANCHLIB`
> Branch library variable

- src/views/objectBrowser.ts
While looking at another PR, I noticed we were changing a lot of attributes of members when the user has the 'objects as lowercase' option enabled.
This replaces two maps with a function which corrects the label casing (the original intention).
> Replace mapping with label fixes

- src/api/local/git.ts
Adds missing `filterType` property on Filter object type.
> Add missing property on filter objects

- src/webviews/settings/index.ts
No functional changes, simply reorganised some of items in the Source Code tab to make more sense with some additional seperators.
> Organise inputs in connection settings UI

- src/api/CompileTools.ts
- src/testing/connection.ts
Ensure the reverse does not mutate and returns correctly.
Add test cases to ensure resulting list is correct.
> Tests and fix for library list order

- .vscode/launch.json
- src/testing/index.ts
Adds the ability to run specific tests without running all the tests.
> Ability to run individual tests

- src/api/IBMiContent.ts
* Replace `DSPFD` and `DSPOBJD` with new SQL to fix CCSID issues.
Examples:
2. Ensure Object Browser filters work
> Use SQL methods to fetch object data

- package.json
- src/api/IBMi.ts
This PR hides the connection browser when connecting to an IBM i. It prevents the user from clicking on the connections or doing any changes to the connections when connecting (that would be bad).
1. Connect to an IBM i
2. Connection browser must be hidden when connecting
3. It must show when disconnected
> Hide the connection browser when connecting

- CONTRIBUTING.md
- package.json
- src/api/Tools.ts
- src/instantiate.ts
- src/locale/ids/da.json
- src/locale/ids/en.json
- src/locale/ids/fr.json
Added the ability to refresh an IFS file. Button is located in the top right of the editor, similar to Run Actions. Making use of the pre-existing command `workbench.action.files.revert` from VSCode
1. Open an IFS file
2. Make/Trigger changes to the file elsewhere 
3. Click refresh button, file should update with latest content
> Refresh file

- src/api/IBMi.ts
Initial work for #2088.
Examples:
> Correctly set QCCSID on first connection

- src/api/debug/certificates.ts
Fixes https://github.com/codefori/vscode-ibmi/issues/2147
The certificate generated for the Debug Service from Code for IBM i did not include a `DNS Name` entry for the LPAR's simple hostname in the subjectAltName section.
This PR adds it so now the subjectAltName section contains:
- The IP address
- The fully qualified domain name
- The simple hostname (if different from the FQDN)
1. Stop the Debug Service
2. Delete the existing certificate
3. Generate a new certificate from Code for IBM i
4. Start the debug service
5. From a web browser, go to: https://LPAR_ADDRESS:8005
6. Use the browser to View the certificate
7. Check the `Subject Alt Names` contains three entries
> Added simple hostname to debug certificate subjectAltName

- src/locale/ids/pl.json
This PR is created to add a missing text in PL translations, blocking a pre-release.
> Add placeholder in PL texts

- package-lock.json
- package.json
- src/api/Instance.ts
- src/api/Terminal.ts
- src/api/debug/index.ts
- src/api/local/deployment.ts
- src/extension.ts
- src/filesystems/qsys/QSysFs.ts
- src/instantiate.ts
- src/testing/index.ts
- src/views/ConnectionBrowser.ts
- src/views/LibraryListView.ts
- src/views/debugView.ts
- src/views/helpView.ts
- src/views/ifsBrowser.ts
- src/views/objectBrowser.ts
Resolves https://github.com/codefori/vscode-ibmi/issues/2181
This PR prevents a failing event function from crashing the whole chain (i.e. preventing other functions from being run when connecting/disconnecting).
1. Connect
2. Make sure every view loads correctly
Connecting to PUB400 should show a warning about the failing function.
> Fix event functions chain crash

- src/views/objectBrowser.ts
Fix invalid options for `IBM i: New Library...` command.
> Fix invalid options for `IBM i: New Library...` command

- src/views/ifsBrowser.ts
Fix invalid options for `Upload...` command
> Fix invalid options for `Upload...` command

- src/ui/actions.ts
* This message is now suppressed from commands not starting with CRT
> Log regarding *EVENTF being missing from command string. #2500

- src/api/Search.ts
- src/api/tests/suites/search.test.ts
Fixes #2647 .
Searching through a source file containing members with a `.` in their name would prevent them from being opened from the Search Result view. The paths displayed in the search result view were also truncated.
The member path parsing from grep results has been fixed and it works fine now.
1. Create a few members with a `.` in their name
2. Search for a term that can be found in several of them
3. Make sure path are complete (name + type) and that each result can be opened
> Fixed member search path parsing

- src/ui/actions.ts
This PR changes the notification displayed while running actions to show the path of the file/object/member being processed.
| Type | Displayed path |
| -- | -- |
| Member | `library/file/member.extension` |
| Object | `library/object.type` |
| Local file / streamfile | file URI path |
1. Run an action on multiple targets
2. Checkout the path displayed in the action notification
> Show target path in notification when running an action

- package-lock.json
- package.json
- types/package-lock.json
- types/package.json
Manual bump since the action failed to do it.
> Starting 2.17.1-dev.0 development
